### ISSUE TITLE
Crafting FPS

### ISSUE THREAD

**Issue by DiseasedKitten** [bluemagic123/tModLoader#123]
I have recently returned to modded terraria, and I've noticed some issues that were not present when I first decided to play. The last version of Tmodloader that I was using was 0.8.2.1, and since then I have updated to 0.9.1. Now that I've updated, crafting has become somewhat of an issue. If I leave the crafting menu, the fps crashes and burns. Depending on the amount of available items, the FPS drops by anything from 2-40. I did some small testing before posting this and got some results.

-With tmodloader but no mods, there are no issues with crafting.

-With tmodloader and Thorium Mod enabled, the fps drops by about 15 when leaving the menu.

-With tmodloader and prefixes for enemies, (only adds a few recipes), the fps barely drops. 

By simply keeping my inventory open when crafting, the fps stays stable, but as soon as I leave it goes down until I open and close my inventory again. I believe its worth noting that the rest of the time the FPS stays at 60 unless using some incredibly particle heavy modded weapons.

Specs:
Processor: AMD FX(tm)-6100 Six-Core Processor
Video Card: NVIDIA GeForce GTX 960
RAM: 8.0 GB (DDR3)
Operating System Microsoft Windows 10 (build 14393), 64-bit

**Comment by Jofairden** [comment]
I don't think this issue is tML related. As you stated, it only seems to happen having Thorium enabled, but not with PfE. I do not seem to be able to replicate this issue myself either.

I suggest you mention this issue towards the developers of Thorium instead. Unless you have anything to add to this, this issue thread should be closed.
