### ISSUE TITLE
A Problem with my Worm Boss (Parts Despawning)

### ISSUE THREAD

**Issue by MrButternuss** [bluemagic123/tModLoader#124]
Hello, i just created a Worm Boss like the Destroyer,EoW etc. 
It all works fine, he spawns, he has all animations, Music starts, he attacks me.
BUT.
I dont know why,  but when he gets offscreen or too far away with his Head the Body and the Tail will just despawn :O And after a while the Head despawned too. Idk what to do XD

**Comment by Jofairden** [comment]
May I please mind you of the fact that this section on github is meant to report issues, in this case with tModLoader itself. This issue is not however, so I will close this issue thread. If you require assistance your best bet is to join [our discord server](http://discord.me/tmodloader). I hope you understand we'd like to make sure this section focuses on issues related to the tML API itself.
