### ISSUE TITLE
Custom Extractinator

### ISSUE THREAD

**Issue by Kampfschaf** [bluemagic123/tModLoader#125]
Is it possible to create an Item/Block that works like the Extractinator? I wan't a new that works like that but throw out my items and not the vanilla items like ores.

THX

**Comment by abc123me** [comment]
I doubt it, but you probably could manage the same thing by creating a crafting recipe and making it require your block nearby

**Comment by Jofairden** [comment]
This is possible by using the ModItem's [ExtractinatorUse](https://github.com/bluemagic123/tModLoader/wiki/ModItem#public-virtual-void-extractinatoruseref-int-resulttype-ref-int-resultstack ) hook and the ModTile's [RightClick](https://github.com/bluemagic123/tModLoader/wiki/ModTile#public-virtual-void-rightclickint-i-int-j) hook.

May I please mind you of the fact that this section on github is meant to report issues, in this case with tModLoader itself. This issue is not however, so I will close this issue thread.

**Comment by abc123me** [comment]
Thanks, Ive wanted to implement something similar in my own mod
