### ISSUE TITLE
Converting ExampleBullet to a Grenade

### ISSUE THREAD

**Issue by saeym** [bluemagic123/tModLoader#16]
I want to change the attributes of the ExampleBullet, so that it behaves likea Grenade when colliding with tiles, I was thinking about using the Aitype so that it behaves like Aitype 16 but failed misserably while doing this, can you help me? thanks

**Comment by bluemagic123** [comment]
This Github issue tracker is pretty much just for bugs in tModLoader. If you want help, you could either try posting on the forums, or asking in the discord chat (linked in the forums).

To answer your question though, the ExampleBullet has a lot of custom coding for projectiles, so that might get in the way.

**Comment by saeym** [comment]
Well can you help me or not?

**Comment by saeym** [comment]
I want to create explosions when the example sword collides with the Tiles in terraria, is it possible?
