### ISSUE TITLE
Accessory Slots go offscreen when above normal amounts

### ISSUE THREAD

**Issue by Delfite** [bluemagic123/tModLoader#1911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Whenever I use mods that add extra accessory slots (can be any mod, a good example being Cheat Sheet) instead of them going off to the left of the screen (towards the player's inventory) like it used to in Terraria 1.3, it now goes off to the right side wherein it becomes impossible to access without downscaling your UI in the settings screen due to it just leaving the screen with only the left-most edge being visible but not interactable.

### Steps to reproduce

1. Go to the Workshop (or the in-game browser) and download any mod that allows the player to have more accessory slots.
2. Increase your available slots to any value (Make sure to have UI scaling turned up if you have it set to something low)
3. Welp, there go those extra slots :|

### Expected Behavior

I should be able to see all my accessory slots and not be mildly annoyed after not being able to see my extra accessory slots

### Actual Behavior

My extra accessory slots go offscreen.

### Reproduction frequency

100% of the time no matter the mod

### Additional Information

I've only been able to find 2 mods that add accessory slots, Cheat Sheet and Extra Accessory Slots.
Hope this helps.

**Comment by LonelySauce** [comment]
Oh yeah forgot to mention this in the report:
Mods like "Antisocial" and "Any Accessory in Social Accessory Slots" will have their effects negated by mods that alter the maximum allowed accessory slots. No idea why this would be happening but hopefully you can get this fixed too.

**Comment by Chicken-Bones** [comment]
Can you send us a screenshot?

**Comment by LonelySauce** [comment]
92% UI Scale:
![20211016213528_1](https://user-images.githubusercontent.com/23504262/137606838-6721b3dc-3efe-4ada-9648-2b392bc0fdfe.jpg)

106% UI Scale:
![20211016213542_1](https://user-images.githubusercontent.com/23504262/137606848-6b13f135-337f-4071-886a-7acd60896a4d.jpg)

**Comment by LonelySauce** [comment]
Can't scroll by clicking or using the scroll wheel, but the button does switch between the two modes.
Also that extra slot to the left isn't a bug, it's a mod called "Wing Slot Extra" which adds a slot for wings to be put in.

So yeah, I guess that kinda solves my problem except for not being able to scroll.
Alright well thanks for telling me about the tiny button I can hardly see that solves me problem completely lol

**Comment by Solxanich** [comment]
@Chicken-Bones - more concerning to me is the claim that scrolling via mouse wheel doesn't work. Its supposed to, so I'll have to check in to that.

With respect to wing slot mod, I thought they already ported in to ModSlot, but guess they kept their custom position. Almost certainly conflicts with stacked display. Happy to change default to stack instead of scroll if we want 1.3 familiarity.

@LonelySauce  when you are trying to scroll, were you using the mouse wheel while hovering over that right most column of slots? Just want to confirm info before I look

**Comment by LonelySauce** [comment]
@Solxanich I can't remember but I'm 99% sure that I was hovering over the accessory slots when I was scrolling as I did try to scroll while hovering over the scroll bar

Also, please do make the stacked view default so reports like this don't pop up ever again. I'm sure it would save everybody the confusion since the scroll bar is incredibly thin which is why I thought they were accessory slots just offscreen
