### ISSUE TITLE
Cannot open 'Mod List' (freezes) from Main Menu

### ISSUE THREAD

**Issue by cchrisdragon2730** [bluemagic123/tModLoader#1949]
### Version

Latest Official

### OS

Mac

### Platform

Steam

### Description

First of all, when I run Tmodloader from Steam normally, I cannot even get to the Main Menu, and am stuck on 'Finding Mods'. However, by holding 'Shift' during the Tmodloader opening process I can bypass the 'Finding Mods' freeze and arrive at the Main Menu. Once at the Main Menu, I plan to go to 'Mod List' to enable my mods. However, once I press 'Mod List', the game freezes on this screen (photo attached).

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7508789/client.log)

### Steps to reproduce

First of all, when I run Tmodloader from Steam normally, I cannot even get to the Main Menu, and am stuck on 'Finding Mods'. However, by holding 'Shift' during the Tmodloader opening process I can bypass the 'Finding Mods' freeze and arrive at the Main Menu. Once at the Main Menu, I plan to go to 'Mod List' to enable my mods. However, once I press 'Mod List', the game freezes on this screen (photo attached).

### Expected Behavior

The 'Mods List' should load and allow me to see a full list of my mods

### Actual Behavior

Freeze at loading the Mods list

### Reproduction frequency

All the time.

**Comment by cchrisdragon2730** [comment]
<img width="1440" alt="Screenshot 2021-11-10 at 12 04 53 AM" src="https://user-images.githubusercontent.com/68218715/141025511-1e18243c-b703-4bca-9ba7-857c985e60de.png">

**Comment by Solxanich** [comment]
Hello,

As with anything of this support help nature, a good starting point that I like to recommend is consulting our discord: https://discord.gg/tmodloader

For this particular problem, could you please answer the following questions:
1) Is the Mac you are using an M1 (Apple Silicon) computer? 
2) Assuming yes to question 1), is your problem already covered in any of the following: #1582  or #1903 ?
3) Have you asked about this in the Discord yet? 

An early theory I can give is that the tmodloader app is being prevented from accessing other file locations, such  as those where mods are stored. This is historically due to antivirus programs, but has also been seen on Apple Silicon more recently.
Note, the 1.3 version will likely never support Apple Silicon, however the 1.4 version (an alpha is available through Discord) currently provides support for M1s.

**Comment by cchrisdragon2730** [comment]
1. Yes my Mac runs on M1.
2. Unfortunately neither of threads you suggested have helped my issue.
3. No I have not, but I have been looking all over the Terraria forums to
solve this issue but to no avail.

I will try the 1.4alpha version instead, and get back to you.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
