### ISSUE TITLE
Deleting a mod and redownloading causes it to fail and refresh the browser

### ISSUE THREAD

**Issue by Truhard** [bluemagic123/tModLoader#1952]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Deleting a mod and reloading, then attempting to redownload the mod results in no successful download and the browser refreshing

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7513769/client.log)

### Steps to reproduce

https://user-images.githubusercontent.com/72954250/141140218-521e578c-19c8-4a74-8299-7c2b19b66cc7.mp4

### Expected Behavior

Redownload

### Actual Behavior

Fails to redownload, refreshes browser

### Reproduction frequency

100% by multiple people

**Comment by Solxanich** [comment]
Thanks for making this issue for this known problem. 
To summarize the problem for whoever wants to look at fixing, Steam's download manager caches the installed workshop items at the start of the game, and assumes at minimum those items are installed throughout the session.
Nominally than, Steam should uninstall the unsubscribed items at the end of the session, assuming the player subscribed to them.

The problem is than pretty clear: we shouldn't be deleting mods prior to the game exiting.
The issue with that though is two-fold:
1) we also serve non-steam, who doesn't get auto uninstall since they aren't involved with subscribing, so we have to delete ourselves
2) Our current file system design expects mods to be deleted on request, not at the end of the play session.

It is thus theoretically possible that someone could combine using Main.instance.Exiting event with the delete code to delete mods at the end of session, on top of a ModOrganizer.FindMods blacklist of "deleted mods". 
It would than be possible to undelete a mod by reversing that.
Afaik, this is how Wallpaper Engine works
