### ISSUE TITLE
Update GOG hash from 1.4.2.3 to 1.4.3.

### ISSUE THREAD

**Issue by EtherTyper** [bluemagic123/tModLoader#1984]
### Do you intend to personally contribute/program this feature?

No

### Description

Update GOG hash from 1.4.2.3 to 1.4.3.

### What does this proposal attempt to solve or improve?

Currently, both the 1.4 alpha and tModLoader 0.11.8.5 require a copy of the GOG version of Terraria.exe from 1.4.2.3, which is no longer available for download.

### Which (other) solutions should be considered?

N/A

**Comment by JavidPack** [comment]
It's a bit of a pain and time investment to publish an update for the 1.3 tModLoader so frequently, and since terraria is still updating with hotfixes for the next few weeks we assume, we'll probably hold off on updating the hashes and pushing a new update for 1.3 tModLoader until those are complete.

Gog users who had tmodloader since before the 1.4.3.x updates will still work due to our checking system, so only new tModLoader users that use GOG who installed tModLoader for the first time after 1.4.3 released are affected. For those people, they can use the gog client to download 1.4.2.3 as a temporary solution.

Once we get word that 1.4.3.x hotfixes are finished, we'll release an update for 1.3 tModLoader. 1.4 tModLoader will be updated within a day or so of each hotfix, as those are automated.

**Comment by p33t3r** [comment]
>…only new tModLoader users that use GOG who installed tModLoader for the first time after 1.4.3 released are affected. For those people, they can use the gog client to download 1.4.2.3 as a temporary solution.

I'm afraid this is not correct, as the OP's (and my) problem is that 1.4.2.3 is no longer officially available from GOG.com.
Any ideas for other solutions, except for trying to download 1.4.2.3 from less reputable places and hoping you get a correct virus-free version?

**Comment by EtherTyper** [comment]
@p33t3r I think he is correct. While you cannot get 1.4.2.3 through the backup installers available on the GOG.com website anymore, you can still get 1.4.2.3 by downgrading your Terraria installation in GOG Galaxy.

<img width="617" alt="Screen Shot 2022-01-06 at 1 12 22 PM" src="https://user-images.githubusercontent.com/16024539/148438045-8009986f-3196-43f9-ba74-4efcd727806a.png">

**Comment by EtherTyper** [comment]
> Any ideas for other solutions, except for trying to download 1.4.2.3 from less reputable places and hoping you get a correct virus-free version?

@p33t3r My suggestion would be to purchase the Steam version and build tModLoader from source, with the hash check updated or removed. That's what I did.

**Comment by JavidPack** [comment]
We're still compiling some small changes for the 1.3 tmodloader, so a release isn't imminent. The current expectation for gog users is to use gog galaxy to downgrade for now, as seen above. You don't have to buy it again on steam.

**Comment by p33t3r** [comment]
Found the way to downgrade, thanks to all. This can be closed now, right?

**Comment by EtherTyper** [comment]
@p33t3r I don't think so. The hash check still needs to be updated (eventually.)
