### ISSUE TITLE
Fullscreen Windowed missing (Settings/Video/Resolution/Borderless Window option missing)

### ISSUE THREAD

**Issue by jsahoka** [bluemagic123/tModLoader#2020]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

The option to use "Fullscreen Windowed"  is missing in the latest Tmodloader (it is available in terraria still)
On discord there was mention that the standard fullscreen option would be borderless windowed now but this does not seem to be the case.

I use 1 monitors, my main monitor is an 3440 x 1440 (WQHD) screen, the second monitor is a regular 1080p resololution.

When in fullscreen mode, if you click in the second monitor, Tmodloader minimizes
When in windowed mode if you click in the second monitor, Tmodloader stays active/in focus. 

Windowed mode has the titlebars visible which is less then ideal. The option "Borderless Window" should fix that, but it is not available in the menu
![2021-12-04 14_19_15-Terraria_ May the blocks be with you](https://user-images.githubusercontent.com/2257011/144711782-524a1fe8-524f-47cf-a680-7a6cff4cf6ab.png)

**Comment by Solxanich** [comment]
To clarify; 
1) exclusive fullscreen is gone, Microsoft has been killing it for a good 4+ years now. Terraria has it as a legacy app, and good chance it won't work after windows 11.
2) borderless window is already implemented. This is what the "Go Fullscreen" button does. 
The other button you are thinking of was for exclusive fullscreen
3) the actual issue here is the question of why the window is getting minimized - I would presume this is due to XNA/FNA being designed for single monitor setups and not properly supporting dual monitors

**Comment by jsahoka** [comment]
Hey Solxanich, thanks for your reply.
I just tested it, it does do a little more then just minimizing the screen. It also mutes the background music. 
I would think that if it is indeed just a minimize but the game would be in borderless windowed mode, the music would keep playing right?

**Comment by Solxanich** [comment]
Not necessarily, no.
Most programs when minimized are muted, windowed or otherwise.

In the most likely design, XNA looks for if the player leaves the game (ie window not active), and forcefully minimizes it to prevent any weird screen softlock issues, again making an assumption that it's single monitor display.

This can probably be modified either through an FNA launch parameter or code; main thing is that the issue here want resolved is forced minimization on a dual screen

**Comment by Solxanich** [comment]
Actually, just double checked, we are currently using borderless fullscreen, not borderless windowed.
Apologies for the confusion there.
The FNA code is pretty bad at providing the right information.
So, yes, borderless windowed is missing and instead borderless fullscreen is being used (arguably a weird setting choice)

**Comment by jsahoka** [comment]
Thanks for clarifying that.
Is this something that could/will be fixed in an upcoming release?

**Comment by melancholicMathematics** [comment]
hope still shines for the future, I still believe

**Comment by MonChoubidouDAmour** [comment]
> hope still shines for the future, I still believe

That is hopeful.

**Comment by Chicken-Bones** [comment]
This will be available:
- On Steam Preview in September
- On Steam Stable in October
- https://github.com/tModLoader/tModLoader/actions/runs/2916536668 Now

**Comment by Chicken-Bones** [comment]
To clarify, there is still no 'borderless fullscreen' _option_, because now regular full-screen is truly borderless (doesn't minimise on focus loss)

**Comment by JavidPack** [comment]
I'm testing this on 2022.9.47.4 (october stable as of now) and the window still minimizes when clicking out (on my 2nd monitor.)

**Comment by steviegt6** [comment]
> I'm testing this on 2022.9.47.4 (october stable as of now) and the window still minimizes when clicking out (on my 2nd monitor.)

Still minimizes for me on the latest October stable as well.

**Comment by markedone66** [comment]
can confirm, its still happening even  in november. Borderless window just doesnt work  on Tmodloader. terraria works fine. I hope it gets fixed is mega annoying.

**Comment by steviegt6** [comment]
I should get around to updating my Borderless Terraria mod to be a proper overhaul to the windowing system.

**Comment by PixusPanic** [comment]
While I don't mean to bump the topic, I can easily confirm that I'm having the same issue. While it's minor, it's definitely annoying to not be able to see the game and have to click on it in the task bar every time I want to focus back into it.

**Comment by TheHarelator** [comment]
still waiting for a fix
