### ISSUE TITLE
[1.4] Infinity mod list update

### ISSUE THREAD

**Issue by Domaman202** [bluemagic123/tModLoader#2041]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

![image](https://user-images.githubusercontent.com/51743763/145717744-d52850e8-e013-4388-8117-ae207dd5dc1e.png)

If there are installed mods, the list of mods is updated endlessly

**Comment by Solxanich** [comment]
This is likely caused by a specific mod. 
If you had posted the log file, I could have told you which one, but no matter.

If you can identify which mod is causing the problem, than that would help significantly. 
You can also uninstall mods through Steam's Workshop page - you will likely need to do that for the poor coded mod in order to fix this.

**Comment by Domaman202** [comment]
ok thx

**Comment by Domaman202** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/7709214/client.log)

**Comment by Domaman202** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/7709215/client.log)

**Comment by Domaman202** [comment]
this a Rothur Mod problem
