### ISSUE TITLE
[1.4 Alpha] Cannot launch game.

### ISSUE THREAD

**Issue by TeddyJi** [bluemagic123/tModLoader#2131]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Only this machine had the problem. Other machines including virtual machines can launch the game properly.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8000713/client.log)

### Steps to reproduce

1. Install Terraria and launch Terraria.
2. Compile/Install tModLoader 1.4.
3. Launch game.

### Expected Behavior

Launch the game properly.

### Actual Behavior

After the cmd.exe-like window, this pops out.
![1](https://user-images.githubusercontent.com/54200073/152484710-36d8f977-4f35-4ca2-b2df-30076a5fe151.png)

### Reproduction frequency

Always

### Additional Information

Reinstalled Steam, Terraria, tModLoader, dotnet. No use. Other PCs work fine, only this couldn't.

**Comment by direwolf420** [comment]
The issue seems to be caused by another existing SDL2 existing on `PATH`.
If you want to fix this yourself, try visiting [this](https://www.java.com/en/download/help/path.html) for more info, and try removing the SDL2 path from it, or changing it to the tml one.

As referenced here: https://github.com/tModLoader/tModLoader/issues/2110#issuecomment-1024967471

**Comment by TeddyJi** [comment]
Thanks for the help. The issue was fixed after deleting the QEMU path. Btw, another "Stack overflow" with repeating logs should be fixed by using "dotnet tmodloader.dll" in source folder. :)
