### ISSUE TITLE
(1.4 Alpha) When opening player select it glitches

### ISSUE THREAD

**Issue by Commercials** [bluemagic123/tModLoader#2144]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The game starts shaking and the background is also not moving.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8045055/client.log)

### Steps to reproduce

1. Open tmodloader 1.4 alpha
2. press singleplayer
3. glitch

### Expected Behavior

not glitching and should be able to pick a character and move on to world select.

### Actual Behavior

glitching and cant do anything

### Reproduction frequency

everytime i open player select on tmodloader alpha.

### Additional Information

I don't know, this started around January 9, 2022

**Comment by iamrusskih** [comment]
Two days ago tML was updated. That was very expected update has marked as "**[Super Breaking"](https://discord.com/channels/103110554649894912/928283223077830686/940749043968147566)**. Most of mods are broken, you should disable all mods to continue playing and wait for mods updates

**Comment by Solxanich** [comment]
Data Oriented Tiles has since been implemented, so this loading issue is due to mods that haven't been keeping up. Pretty much as iamrusskikh described  

Any remaining issues pertain to the mods you are using not being able to keep up with tML changes. Disable those in the event of that being the case.
Closing in light of that.
