### ISSUE TITLE
Allow older Terraria.exe builds in hash check

### ISSUE THREAD

**Issue by FakeDomi** [bluemagic123/tModLoader#2203]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Keep old hashes to compare against.

### What does this proposal attempt to solve or improve?

Since my friends use the Steam version of TML, I have to update my server and my GOG version everytime there's an update.
Version juggling with GOG quickly becomes annoying. I had previously installed a fresh GOG Terraria 1.4.3.2 (to use the TML 0.11.8.6 build) after having already installed Terraria 1.4.3.6 v1, and now GOG doesn't let me update either of my installations.

If TML would accept older versions of Terraria one could just set a copy of Terraria aside without worrying having to worry about updating two installations which isn't even supported by GOG.

### Which (other) solutions should be considered?

- Reconsider how TML detects installations. Maybe just check whether the file/product version is at least the version TML is based on. The game won't run properly without the resources anyways.

**Comment by JavidPack** [comment]
One of the benefits of the checks is to ensure that the gog user is using the correct version of Terraria and associated data files. This helps avoid troublesome troubleshooting issues that could happen when texture files or other files change during updates. It is true that many hotfixes don't change any texture files, or other dependent files, so it seems reasonable to allow running tmodloader with an older terraria, but in practice it would take a lot of effort to verify that things will work 100% correctly in each of these situations. 

Due to this approach making things less reliable, we won't be pursuing this suggestion.

For the record, the 1.4.3.6 v2 thing never happened before, and I've made some code changes that might help avoid confusion for that situation.
