### ISSUE TITLE
Manual Install is Not Possible, no CSteamworks.dll in current steam release of Terraria (1.4.3.6)

### ISSUE THREAD

**Issue by mav1o1** [bluemagic123/tModLoader#2248]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Latest Steam Release of Terraria does not contain CSteamworks.dll, making manual installation from the steam version impossible.

### Steps to reproduce

1. Download a fresh installation of Terraria off of steam. (If you have a version of Terraria that has been updated from a previous version this will not work.)

### Expected Behavior

CSteamworks.dll should be present in the /Terraria folder.

### Actual Behavior

CSteamworks.dll isn't present in the /Terraria folder.

### Reproduction frequency

100% of the time.

### Additional Information

SteamDB does not show CSteamworks.dll in the current depot.
https://steamdb.info/depot/105601/

**Comment by mav1o1** [comment]
The Steam release of tmodloader contains CSteamworks.dll, making this irrelevant for those downloading from steam.

**Comment by mav1o1** [comment]
Additionally, other people's CSteamworks.dll files do not work.

**Comment by JavidPack** [comment]
The file should be there when you download tmodloader from steam already, I checked and the latest tmod version download from steam has the files you need.

I see that the zip here doesn't have it, since those are steam specific files, but if you download tmod from steam as we recommend, you'll have the files.

**Comment by EnderLuca41** [comment]
Players who have Terraria via Family Share are still screwed...

**Comment by JavidPack** [comment]
> Players who have Terraria via Family Share are still screwed...

No, last we heard back from someone on this, it was launching tmod that had issues, not installing. Our instructions say to just copy the `steam_appid.txt` file over from the Terraria install to avoid the launching issue.

https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#steam-family-share-installation 

If that isn't the case anymore, we can look into this further.

**Comment by EnderLuca41** [comment]
I have copied the steam_appied.txt into the tModLoader folder, but it still fails, because of the missing CSteamworks.dll file.

Here the error:
("Das angegebene Modul wurde nicht gefunden" means "The specified module was not found")

System.DllNotFoundException: Unable to load DLL 'CSteamworks': Das angegebene Modul wurde nicht gefunden. (Exception from HRESULT: 0x8007007E)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize() in tModLoader\Terraria.Social.Steam\CoreSocialModule.cs:line 26
   at Terraria.Social.SocialAPI.LoadSteam() in tModLoader\Terraria.Social\SocialAPI.cs:line 76
   at Terraria.ModLoader.Engine.InstallVerifier.CheckSteam() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 99
   at Terraria.ModLoader.Engine.InstallVerifier.InstallCheck() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 88
   at Terraria.ModLoader.Engine.InstallVerifier.get_IsValid() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 19
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode) in tModLoader\Terraria.Social\SocialAPI.cs:line 28
   at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 245

**Comment by JavidPack** [comment]
Did you try installing tmodloader via steam? That's how you get that file. Our guide says you need to install via steam, then swap out the steamappid.txt file to get it to launch. You shouldn't be downloading tmodloader from here.

**Comment by EnderLuca41** [comment]
You cant install tModLoader over Steam when you have Terraria only over Family Share.

**Comment by davidkassa** [comment]
These instructions never worked for me and I went back and forth between family share accounts to try all the combinations with no luck and ended up having to use the zip version instead.

**Comment by JavidPack** [comment]
I see, then somewhere along the way the instructions have been incorrect. I'll look into what we can do.

**Comment by JavidPack** [comment]
K, I've included the files in the v0.11.8.9 release, hopefully this will help blaze a path for family share users to be able to install and launch tmod. I assume you still will need to copy over the `steam_appid.txt` file the install guide mentions.

**Comment by dozzzz02** [comment]
> K, I've included the files in the v0.11.8.9 release, hopefully this will help blaze a path for family share users to be able to install and launch tmod. I assume you still will need to copy over the `steam_appid.txt` file the install guide mentions.

Whatever you are recommending, it doesn't work yet. Has the team not contacted Steam about this issue before?

**Comment by JavidPack** [comment]
We've done more work on family share support lately. It should work at least for 1.4.4-preview and stable users. I'm not sure what the status is for 1.3 users, but I figure most will want to use updated tModLoader.

If anyone is still running into issues with manual install, we can help in Discord chat, but I think this issue is likely solved at this point so I will be closing.
