### ISSUE TITLE
When 1.4 comes out let there be an option to downgrade in the beta tab

### ISSUE THREAD

**Issue by FlutterTree** [bluemagic123/tModLoader#2301]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

When tmodloader 1.4 comes out there is no information that I can find that you will be able to stick with 1.3.5 to play mods that either are designed for 1.3.5 or play mods that wont get updates because their devs have moved onto new projects. I hope that when 1.4 tmodloader does come out that you will be able to downgrade. and if this is a planned feature please add it to the FaQ on the steam discussions because it is quite worrying not knowing if it will be supported or not.

### What does this proposal attempt to solve or improve?

This will allow old mods to still be able to be played and also allow modders who like the 1.3.5 version of terraria more than 1.4 to produce mods for a version they like/ a version their mod is designed around.

### Which (other) solutions should be considered?

a way for old mods to be auto updated for 1.4 which sounds very unreasonable but at the moment it is super hard to downgrade anything on steam and I'm also going to assume that the browser would end up breaking for older versions and not every mod has active support, some mods like imksushis mods haven't been updated in 2 years its unlikely for them to come back and update their mod personally you would have to hope someone else updates it or just be out of luck.

**Comment by Solxanich** [comment]
Hi, thanks for asking!

Our Discord is the primary information source for all things tml dev related.
The discord answers the question there; when 1.4 is made to be the default, 1.3 will be moved to be one of the Steam Beta options so that it can persist.

We are well conscious of the fact that not all mods will make the jump to 1.4, and will proceed accordingly.

With regards to Steam discussions, I'll pass this feedback along, but no guarantees of anything; again, the discord is THE most up to date information source
