### ISSUE TITLE
[1.4] Biome registration fails in certain parts of the world

### ISSUE THREAD

**Issue by Lion8cake** [bluemagic123/tModLoader#2365]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

In certain parts of the world the game completely fails to register a modded biome. 
This affects anymod with a biome as NPCs can't spawn which might be required for the mod's progression.

### Steps to reproduce

1. Create a modded biome
2. Use a tool (modded Biome solution, copy paste tool, ect) to spread the biome blocks all around

### Expected Behavior

The biome should always be registered in these areas where they are not.

### Actual Behavior

The modded biome is not being registered 

### Reproduction frequency

Almost 100%

### Additional Information

I am unsure where or why the biomes aren't being registered
What the biome is currently doing
![Capture 2022-05-11 19_11_12](https://user-images.githubusercontent.com/69915693/167815522-62b1c789-de25-43ce-bee3-6d6904fd1698.png)
What the biome should be doing (replicated by just copying the section of where the previous screenshot was taken over to an area where the biome is registering)
![Capture 2022-05-11 19_20_17](https://user-images.githubusercontent.com/69915693/167815819-b752482d-3baa-4fb3-afae-f292326e3913.png)
.

**Comment by direwolf420** [comment]
Please provide a sample mod (its source as zip) that you can use to reproduce this behavior with.

**Comment by Lion8cake** [comment]
Here is a mod I threw together in 30 minutes which I also tested and it does the same biome unregistering thing that my main mod does/what this thread does. 
https://drive.google.com/file/d/1rpd_hCdI5KRDar9O1X483aRF8qLNAmno/view?usp=sharing

**Comment by direwolf420** [comment]
Did you resolve this? How?

**Comment by Turtle16668** [comment]
This may be a bit late, but I believe your issue is that you aren't actually registering your custom biome. In the files provided, you have the surface and underground background styles as well as the water stuff, but you aren't actually registering those into a custom biome. I'm not too great at making biomes, as I don't yet understand how the bestiary stuff works yet, but I have provided a simple text document of how to register a surface biome.
[Example Biome.txt](https://github.com/tModLoader/tModLoader/files/11858105/Example.Biome.txt)
