### ISSUE TITLE
[1.4] Failed to publish the item to steam! The content folder for the published item is missing?!

### ISSUE THREAD

**Issue by xKirtle** [bluemagic123/tModLoader#2375]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When trying to publish a mod (whether for the first time or just an update)

### Steps to reproduce

1. Get a fresh install of tModLoader (or just verify the game files)
2. Create a mod (and build it)
3. Try to publish it to the Steam Workshop

### Expected Behavior

The mod should be published and a web page should open in the steam overlay with your workshop mod.

### Actual Behavior

Error message: Failed to publish the item to steam! The content folder for the published item is missing?!

### Reproduction frequency

Always.

**Comment by dhozou** [comment]
After applying #2376 and checking that `Steamworks.NET.dll` had been properly replaced, publishing still failed with the same error for me. Snippet from `~/.local/share/Steam/logs/workshop_log.txt`:
```
[2022-05-22 20:38:56] [AppID 1281930] Upload starting for workshop item 8583993930675126272 by AppID 1281930
[2022-05-22 20:38:56] [AppID 1281930] Getting Workshop info for item 8583993930675126272 failed : File Not Found
```

Deleting the directory `~/.local/share/Terraria/tModLoader/Workshop` solved the problem. I think the issue was a stale `workshop.json` from my previous failed uploads.
