### ISSUE TITLE
Can't use tmodloader (GOG)

### ISSUE THREAD

**Issue by OofCrafter** [bluemagic123/tModLoader#2386]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

When I extract and place the files in the correct locations and attempt to launch tmod, i get an error (see image)
![image](https://user-images.githubusercontent.com/105608270/168492389-e0a439b4-58d7-4d49-97e8-0c24aae46dcd.png)
The thing is, I have that exact version of Terraria as an exe file. Please help me out here, I just want to use mods on Terraria

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8695921/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/8695922/server.log)

**Comment by JavidPack** [comment]
You'll need to download [0.11.8.9](https://github.com/tModLoader/tModLoader/releases/tag/v0.11.8.9) first, since 0.11.8.7 won't work anymore. And you need to download the absolute latest terraria, on gog it is labeled 1.4.3.6 B or something. It has the new wiki link on the bottom right of the main menu, not the old wiki link. The older 1.4.3.6 won't work.

**Comment by OofCrafter** [comment]
After downloading 0.11.8.9 and putting the file in the correct location, it just prompts me to install tmodloader on steam, and I don't own the steam version of the game.

**Comment by JavidPack** [comment]
Did you do step 3? https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

**Comment by Val3h02** [comment]
I have the same problem and I can't solve it. I even tried to follow all the steps but it doesn't work for me
