### ISSUE TITLE
CloneDefaults makes item register to others as the vanilla item

### ISSUE THREAD

**Issue by Ouroel** [bluemagic123/tModLoader#2401]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

```cs
public override void SetDefaults()
{
	Projectile.netImportant = true;
	Projectile.CloneDefaults(ProjectileID.DeadlySphere);
	AIType = ProjectileID.DeadlySphere;
	Projectile.width = 32;
	Projectile.height = 32;
	Projectile.friendly = true;
	Projectile.minion = true;
	Projectile.penetrate = -1;
	Projectile.timeLeft = 18000;
	Projectile.ignoreWater = true;
	Projectile.tileCollide = false;
	Projectile.minionSlots = 0;
}
```

You put this `SetDefaults` in one `ModProjectile` file

and in `GlobalProjectile.SetDefaults` the file will detect modded projectile as vanilla type

```cs
public override void SetDefaults(Projectile proj)
{
	if (proj.type == ProjectileID.DeadlySphere)
		Main.NewText("true")

	Main.NewText(proj.ModProjectile) //null
}
```

There is currently no way to detect the projectile's actual ID/etc.

**Comment by JavidPack** [comment]
GlobalProjectile.SetDefaults will be called twice in this situation, the first time it should appear as the vanilla projectile, the second time you should be able to detect it as a modded projectile. I think it should all work out as it is?

**Comment by direwolf420** [comment]
The issue is the first call, which operates under a wrong assumption, as the actual projectile this GlobalProjectile is attached to has a different type than the one being checked. Another example where this is problematic:

First call:
![Screenshot_10](https://user-images.githubusercontent.com/15894498/169600881-4a03f70a-04fe-4b15-a535-b2c726c19d96.png)
Second call:
![Screenshot_11](https://user-images.githubusercontent.com/15894498/169600882-3544e8f6-4961-467c-b0dc-075836acc8da.png)
State after second call (and continuing into the lifetime of the projectile whenever it is spawned too)
![Screenshot_9](https://user-images.githubusercontent.com/15894498/169600667-6190ed13-2b66-4e59-a663-dd5f68fc122d.png)

replace list.Add with something less sensitive (like dict.Add)
