### ISSUE TITLE
Save mods to the mods folder rather than steam workshop folders

### ISSUE THREAD

**Issue by Mangochicken13** [bluemagic123/tModLoader#2418]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Having an option to toggle between the default save paths and having all the mods in one place would be a good (in my opinion) QoL change, especially when sharing or deleting mods. There are currently issues with deleting mods with steam not recognizing that the workshop item is gone, and remaining subscribed. This leaves the "Update all" button in the mod browser, which when clicked attempts to update the mods and fails, not re downloading them either. 

### What does this proposal attempt to solve or improve?

This would (probably) fix issues with updating mods and steam workshop not recognizing mods being deleted

### Which (other) solutions should be considered?

These problems could be fixed without changing the save path if deleting a mod unsubscribed you from it's steam workshop page, which could potentially solve all of the associated problems, but i don't know personally if that is possible (although i don't know if the original suggestion is either)

**Comment by Mangochicken13** [comment]
As an aside, if this suggestion is dumb, feel free to remove it

**Comment by direwolf420** [comment]
#2406 potentially related PR

**Comment by Solxanich** [comment]
So this is kind of due to several problems on steam's end:
1) We don't actually have any control over where Steam installs workshop items, nor can we guarantee a consistent location to put save data. We are looking to free up a button space on the mods menu to be able to add an 'open Workshop location' button.
2) Now the issue of deleting mods:
- The Steam behaviour is to uninstall and complete unsubscriptions after the game closes. It does NOT uninstall until the game is closed. 
- On GoG platforms, this contradicts as the behaviour that is used to uninstall mods afterwards is not present, so we now rely on directly deleting the files and modifying Steam records.

-----------------------------------------
So for GoG users, the current tModLoader behaviour is the only option.

For Steam Users, yes, we do unsubscribe and resubscribe people via the API and do what we can to actually clear them out. But again, if Steam doesn't update itself until the next launch of the game, we get all sorts of weird behaviour.

---------------------------------------------------------

Now the core of the issue you are presenting is something I've debated long over: 
Should Workshop Items, for Steam Users, be left to be uninstalled/deleted by Steam after the game ssesion?
It's possible to do as such, but also gets quite messy and may leave extra files that Steam doesn't get rid of.

The ideal solution is the error prompt that is supposed to show up actually does, and tells people to restart their game and/or subscribe and unsubscribe in steam workshop.

----------------------------------------------------------
Now with respect to the mod browser, the fix is more straightforward - we just need to reset the cache on the browser when items are deleted, which is something not happening today, and an important factor in what you are seeing.

**Comment by JavidPack** [comment]
The recent mod loading rework should address the issues contained in this issue.
