### ISSUE TITLE
Localized Text isn't loaded the first time.

### ISSUE THREAD

**Issue by Pop000100** [bluemagic123/tModLoader#2542]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Localized text isn't loaded until it has been loaded a second time.
source code included in the mod.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8884438/client.log)

Look at the two "[.NET ThreadPool Worker/INFO] [LoadingTest]" lines

### Steps to reproduce

1. Enable Mod
2. Load
3. Reload

### Expected Behavior

TModloader would successfully retrieve the value stored at that key.

### Actual Behavior

Text is just the key value for the localized text

### Reproduction frequency

100%

### Additional Information

Here is a bare bones mod to demonstrate the issue
[LoadingTest.zip](https://github.com/tModLoader/tModLoader/files/8884513/LoadingTest.zip)

**Comment by steviegt6** [comment]
https://github.com/tModLoader/tModLoader/blob/205534eda857f6f3d852c9068be0afec9b112804/patches/tModLoader/Terraria/ModLoader/ModContent.cs#L337
Languages are refreshed *after* `PostSetupContent`. The reason it "works" the second time is because that translation is left over from your mod last time it was loaded (it's cleared when languages are refreshed).

**Comment by Pop000100** [comment]
Alright, I guess PostAddRecipes Works.
This can be closed if you want.
