### ISSUE TITLE
Multiplayer Bosses not working!

### ISSUE THREAD

**Issue by max100e** [bluemagic123/tModLoader#27]
I think the title speaks for it self. I can provide any information necessary. (except the fix ofc ;))

**Comment by Chicken-Bones** [comment]
I suppose we could just boot up a server, try and spawn eye of cthulhu and see what happens, but since I can't exactly do that right now, and it's a good exercise in giving quality bug reports.

Give us some more information other than "not working".

1. What you did (right click the summon item/fly around in circles/kill the boss)
2. What you expected (the boss spawns/the boss follows you/the boss drops items)
3. What actually happened (the boss doesn't spawn/the boss just flies off/the boss doesn't drop anything)

and anything else that might be of use like, "we get the message but nothing appears" or "only one player can see the boss" or "it only happens with this specific boss/when it's hardmode/etc"

**Comment by max100e** [comment]
Apologies for the short comment on a big issue.

For me it is possible to create the 'Grand Flare Gun', 'Storm Flare' to create The Grand Thunder Bird. But when using the item (right click the item or shoot a flare) the boss doesn't appear. I am not sure if it spawns but never shows it self or just does not spawn at all. There is no notification on the left bottom. Upon right clicking the item a sound is triggered which is only audibly by the player using the item (even if there are multiple people).

**Comment by Chicken-Bones** [comment]
I assume this is a modded boss? What's the name of the mod? I also assume vanilla bosses work correctly?

**Comment by bluemagic123** [comment]
I've looked into the code for the boss in question, and it looks like a bug in the mod, not tModLoader. The problem is that the spawning code takes place in the Shoot hook, which is only called client-side, when NPCs can only be spawned server-side.
