### ISSUE TITLE
Opening shop gives an error message in the chat.

### ISSUE THREAD

**Issue by B34tingH34rt** [bluemagic123/tModLoader#2786]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Opening skeleton merchant shop while being underground in the gemstone cave gives an error message in the chat.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9229514/client.log)

### Steps to reproduce

For me this error message only appeared while being and opening skeleton merchant shop in the gemstone cave.

### Reproduction frequency

100% when I found this issue. After disabling my own mod issue disapeared

### Additional Information

This error message appears only when I have enabled my own mod, that uses ModPylon feature. There are a few ModPylon tiles that appear in the merchants shop at the same time as I open it.

**Comment by Chicken-Bones** [comment]
Looks like an issue with ExampleGlobalNPC.

**Comment by steviegt6** [comment]
If memory serves me right, the Skeleton Merchant is not considered town npc (by `NPC::townNPC` standards), meaning a new instance will not be created. This causes SetupShop to fail, since the Skeleton Merchant still has a shop.
https://github.com/tModLoader/tModLoader/blob/81073299461b4c6b1727a4d55e6e86c14815a46b/ExampleMod/Content/NPCs/ExampleGlobalNPC.cs#L14-L17

https://github.com/tModLoader/tModLoader/blob/81073299461b4c6b1727a4d55e6e86c14815a46b/ExampleMod/Content/NPCs/ExampleGlobalNPC.cs#L30-L34

**Comment by JavidPack** [comment]
This error seems to no longer be present with recent shop changes.

Talking to Skeleton Merchant will no longer call ExampleGlobalNPC.SetupShop code due to AppliesToEntity. I couldn't see any easy way to detect if a non town npc has a shop or not, so the purpose of the code doesn't cover all cases, but it's better than errors.

**Comment by Chicken-Bones** [comment]
The ultimate way to determine if an NPC has a shop is now `NPCShopDatabase.AllShops.Any(s => s.NpcType == type)`.
It might be worth adding an extra method with a `bool[]` backing set like  `NPCShopDatabase.HasShop(int npcType)`
