### ISSUE TITLE
NPC HitEffect doesn't work for debuffs (eg. cursed flames)

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#2813]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

The title is pretty self explanatory, but I'll provide some more information:

https://user-images.githubusercontent.com/108148176/183512018-ddcdeaec-2d9b-4523-9d3d-8d75a1f71294.mp4

The (example) code showed in the video, which gives the NPC health when damaged:

```cs
public override void HitEffect(int hitDirection, double damage) {
	NPC.life = int.MaxValue;
}
```

### Log File

I couldn't find the "tModLoader-Logs" folder.

### Steps to reproduce

1. Use HitEffect with a visible effect
2. Damage normally, then add any damaging debuff to your NPC
3. See that it only applies to normal damage

### Expected Behavior

Debuff damage should apply to HitEffect.

### Actual Behavior

..debuff damage doesn't apply to HitEffect.

### Reproduction frequency

Always happens.

**Comment by Chicken-Bones** [comment]
@Ozzatron your opinion?

**Comment by JavidPack** [comment]
I'm not sure I follow this one, what is debuff damage?

**Comment by Chicken-Bones** [comment]
Some related discussion was https://discord.com/channels/103110554649894912/445276626352209920/1006279850107084901

**Comment by Chicken-Bones** [comment]
Mostly, buffs and debuffs deal damage without going through the 'strike' system directly, and so they don't trigger some of our hooks. Needs discussion on whether we change this

**Comment by JavidPack** [comment]
@Chicken-Bones Can this be closed with the damage changes?

**Comment by Chicken-Bones** [comment]
Debuff damage is calculated as negative `lifeRegen`. `HitEffect` is not called because there is no _hit_. Vanilla does not spawn dust or other hit effects. 

life regen (DoTs) and drowning are the only vanilla instances of damage being done to an NPC without a strike. New hooks could be considered for this, but I don't know that there are compelling use-cases. 

For the specific use-case illustrated in the video, I believe the author wants to avoid using `NPC.immortal` because of other side effects (homing projectiles perhaps). In this case, I may recommend using an `On_NPC.UpdateNPC_BuffApplyDOTs` hook, and setting `immortal` before and un-setting after.
