### ISSUE TITLE
Support for publish a newer version on stable AND discard preview version

### ISSUE THREAD

**Issue by Solxanich** [bluemagic123/tModLoader#2897]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

It often happens that some modders push to preview an older version, than find they want to push a new version to stable.

The problem with that is the versioning for tmodloader & the mods does not facilitate.

A recommended resolution is to have something akin to:
"Upon publishing to Stable, check if there's a pending mod version on Preview.  In that case, pop up a dialog...
Title: Warning!  Are you sure about that?
You have a pending version of this mod in Preview.  Would you like to remove it in favor of this release to Stable?  If not, this release will be OVERWRITTEN by the older Preview version at the end of the month.

Replace (default button)              Keep Both Releases
                                                            (red button)"
                                                            
Combined with having a method to delete any mod copies that are higher than the publishing version, similar to the 9999 check today.

### What does this proposal attempt to solve or improve?

Decrease issues with updating mods as pertains to mod browser

**Comment by Chicken-Bones** [comment]
Closing this as unsupported. Once a preview version is published, modders should maintain it. I see no reasonable way to 'un-publish' it.

We discussed `1.0.0.1 for tML 2023.06` being loaded instead of `1.0.0 for tML 2023.07` when the user is on `2023.07` or higher but ultimately decided that this would lead to confusion and accidental breakage. See the full discussion at https://discord.com/channels/103110554649894912/1153604070267953182
