### ISSUE TITLE
Change HookGen naming conventions to reduce import confusion.

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#2930]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Change HookGen to put all the hooks in `On_OriginalTypeName` and `IL_OriginalTypeName` classes. (Eg `On_Player` and `IL_Player`)

### What does this proposal attempt to solve or improve?

Currently, HookGen types share the same name as the original type, just in an `On.` or `IL.` namespace. This means that when you go to import `Tile` from `Terraria`, you end up with 3 suggestions (`On.Terraria.Tile`, `IL.Terraria.Tile`, `Terraria.Tile`). This is annoying and the default is not the one you want normally.

### Which (other) solutions should be considered?

Leave as is or find a way to prevent auto imports of those namespaces.

**Comment by steviegt6** [comment]
I believe this would be incredibly beneficial, and would also just allow us to write cleaner, more concise code that looks better.

The `On_` and `IL_` distinctions make it immediately clear what types are associated with MonoMod HookGen. Being able to reference `Player`, `On_Player`, and `IL_Player` from the same using directive without aliases or weird ambiguities allows us to heavily cut down on additional boilerplate stemming from either writing using aliases or writing out entire namespaces in method declarations.

**Comment by direwolf420** [comment]
> find a way to prevent auto imports of those namespaces.

You can make an exclusion in the mods csproj file, but it's less than ideal in case the csproj updates, as the current code that does the updating just replaces it entirely, and would mess with modders who removed that exclusion.

Overall I agree with moving the hooks to prefixed classes instead of namespaces, as it avoids confusion when using VS "using suggestion" feature

**Comment by Chicken-Bones** [comment]
Delivered in 56f66570219a66095120e64e7f0640d6ba0a6999

**Comment by Tyndareus** [comment]
Late on this one but often have a similar issue where Main ends up being IL or On, depending on how the IDE is feeling.

How come packaging wasn't an expressed option? You keep the project split up so that you don't have this additional bloat in the main project, and if people want to use hooks they pull in the "on.tmod" package or using il with the "il.tmod" package. 

Its a similar thing done for _most_ extensions that find their way on to nuget theres always subpackages or submodules

**Comment by Chicken-Bones** [comment]
I'm not completely sure what alternative you have in mind, and whether or not you like the current solution. Please come to the Discord and ping me in #collaborators (if you don't have access I can give it to you) and we can discuss
