### ISSUE TITLE
Chat tags in multiline tooltips create empty space for no reason

### ISSUE THREAD

**Issue by ThomasThePencil** [bluemagic123/tModLoader#2980]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

mod capability as a modder **and** gameplay as a player. welcome to the real world

### Description

usin' color codes in multiline tooltips seems to make empty space in the tooltip for no reason, like so
![image](https://user-images.githubusercontent.com/8083133/192374362-a71c7b1e-b451-4ec5-9b67-a97caa8b59c7.png)
this stacks with additional color codes and can actually cause the actual tooltip above it to be pushed off of the screen, like so
![image](https://user-images.githubusercontent.com/8083133/192374466-9de1a743-ff46-4b2b-bc39-9510389debef.png)

### Log File

the hell is a log file gonna do here?

### Steps to reproduce

**step the first:** make a multiline tooltip (the "multiline" aspect is critical, as this does not happen with separate lines)
**step the second:** use color codes within your newly-multline'd tooltip
**step the third:** ???
**step the fourth:** observe the empty space that's present in-game, and wonder why that tooltip revamp gets talked up so much when nobody has any concrete progress put forward towards doin' it

### Expected Behavior

there's no empty space at the bottom of the tooltip

### Actual Behavior

didn't I already tell you? there's empty space at the bottom of the tooltip where there shouldn't be

### Reproduction frequency

100% of the time, specifically when usin' chat tags in multiline tooltips. it doesn't seem to happen for anything else

**Comment by ThomasThePencil** [comment]
upon further inspection and thorough testin', this seems to be moreso an issue with the way I replace tooltip lines at the minute (which I do primarily because an "official" method for doin' so does not exist). closin' this as a result, although I *will* come back to this as a point to touch upon when the inevitable tooltip revamp comes around

**Comment by Rijam** [comment]
Happens in the Bestiary too. 
![image](https://user-images.githubusercontent.com/11262234/192392254-7fb3cb1f-dd0e-480c-a5c3-380538e0bef2.png)

The chat tags are not in the localization itself but are applied around the localization.
Repo links:
Localization file: https://github.com/Rijam/FishermanNPC/blob/main/Localization/en-US.hjson#L221
Town NPC: https://github.com/Rijam/FishermanNPC/blob/main/NPCs/TownNPCs/Fisherman.cs#L80
Where the chat tags are: https://github.com/Rijam/FishermanNPC/blob/main/NPCs/NPCHelper.cs#L30

Side note, also notice how the text wrapping is weird. "Angler" could fit on the first line, but it is pushed to the second line.

Removing the chat tag colors:
![image](https://user-images.githubusercontent.com/11262234/192392681-d5fd4dcf-486c-4838-84af-a554bd4fc81d.png)

**Comment by ThomasThePencil** [comment]
...hrm. in that case, I'll reopen this to be looked at by somebody, because it seems chat tags generally just don't play nice

**Comment by Ved-s** [comment]
After some testing I found out that the problem is in `ChatManager.GetStringSize`, it measures string wrong if there is a newline, and a chat tag in this specific order

Minimal test case: `\n[c/abcdef:Color]`
![](https://user-images.githubusercontent.com/53968411/192416919-4fe33317-c99b-4e29-a3bc-c9cc14122d62.png)

Also, text can "overflow" to the next line, `\ntexttexttexttexttext[c/abcdef:texttexttexttexttexttexttexttexttexttext]`
Color tag being measured like it's on a new line
![](https://user-images.githubusercontent.com/53968411/192416657-8b5d9301-294f-4c19-ae2d-b513d1b89ea1.png)

More test cases:

`text\ntext[c/abcdef:Color]text` is broken
![](https://user-images.githubusercontent.com/53968411/192417016-fd886851-8c9a-44f9-9244-e9952b6d96f3.png)

`Test\n[c/abcdef:Color]\n` is broken
![](https://user-images.githubusercontent.com/53968411/192417144-04eb3405-f7e0-457b-b6cd-a7446cd05d1e.png)

`Test[c/abcdef:Color]\n` is good
![image](https://user-images.githubusercontent.com/53968411/192417231-a0736705-84a5-4ef9-9c6d-4b9b11101c80.png)
