### ISSUE TITLE
Game wont load in steam-black box

### ISSUE THREAD

**Issue by CHRONICH** [bluemagic123/tModLoader#3002]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I start the game, the black box will show as it should that it is loading up for a seconde and then it will disapear, and then steam will say not load anymore. Sorry if this is a bad description but idk any other way of putting it

I have tried restarting, uninstalling, have checked everything that could interact with it like antivirus and etc i have looked at the files and nothing seems to be missing,

However, the game won't start

**Comment by JavidPack** [comment]
We need logs or we can't help you (C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader-Logs). This issue is more suitable for our discord chat though, we should be able to help you solve it in real time there.

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
