### ISSUE TITLE
All control schemes in all verions of Tmod and Vanilla enter a unusable and usually irreverable state when alt-tabbing in any window or fullscreen mode.

### ISSUE THREAD

**Issue by ExiledMiner04** [bluemagic123/tModLoader#3013]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

https://www.youtube.com/watch?v=5DTSYt47zTo&t=104s

This occurs in all versions of Terraria when alt tabbing back into the game and touching anything and I mean anything! It can happen in Tmod as well, but its more so a glaring issue in Vanilla. Perhaps you guys can find the bug in the game code and fix it for Tmod and also show it to relogic to also fix in vanilla? It still occurs as of all versions of 1.4 vanilla, Tmod legacy for 1.3, TML 64 legacy branch and TML 1.4. Its not a controller only issue as I once believed, this guys video playing thorium mod with legacy Tmod proves it can happen with keyboard and mouse too. (edited)
YouTube

### Steps to reproduce

1. play normally alt tab off window for a while and click back in.
2. Press any assigned key or any button on an attached controller.
3. Also open inventory and start pressing any button/key on a controller, keyboard or mouse you have mapped.

### Expected Behavior

The game should not assign a new neutral position state when you tab back into the game and also remember what control scheme you are using or properly toggle between the two schemes when it recognizes an input form the opposite control scheme-- not try to do both at the same time.

This is a game breaking issue. closing the game does not fix it only restarting the PC or killing steam and restarting steam fixes it. trying to run Terraria or Tmod loader again dos not fix it usually.

### Actual Behavior

See video and expected behavior sections.

It doesn't matter if you are keyboard and mouse only to play or Controller only (can't really be controller only on a PC), if you touch anything on either after tabbing back in it may break and cause faulty operation of the UI.

It happens if vanilla or using tmodloader it is probably a vanilla code issue that carried over into all versions of TML. It has existed since 1.3.x.

### Reproduction frequency

90% of the time when trying to tab back into the game window even on fullscreen.

**Comment by JavidPack** [comment]
I tried to replicate your issues for a while, wasn't able to replicate them. I'm not sure what is up. 

Since you've mentioned this happens in vanilla, it might be worth reporting in https://forums.terraria.org/index.php?forums/journeys-end-bug-reports.219/ and seeing if there is anything that can be done. 1.4.4 hotfixes still seem to be going on, so if you report this now you might be able to get a fix into the next hotfix release.

I worry that there might be some other common factor between you and the other users with this issue, it might be good to check and see if you can find anything in common with other users, such as those youtube commenters.

As it is, I'll be closing this since there is nothing we can do since we can't replicate, but if anyone else is having this issue, please provide any information you can (here, or on https://forums.terraria.org/index.php?forums/journeys-end-bug-reports.219/). If we can figure something out, we might be able to get this fixed in Terraria.
