### ISSUE TITLE
T mod loader not opening

### ISSUE THREAD

**Issue by Kaptains1** [bluemagic123/tModLoader#3016]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when my friend tries to open t mod loader thru steam it says Windows cannot access the specified device path or file you may not have appropriate permissions

**Comment by JavidPack** [comment]
We can't really help without more information, especially the log files. Also, the discord is a more suitable place for support style questions: tModLoader.net/discord

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
