### ISSUE TITLE
Buff tooltips aren't coloured by chat tags

### ISSUE THREAD

**Issue by stormytuna** [bluemagic123/tModLoader#3018]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Buff tooltips aren't coloured by chat tags
If a buff has a tooltip `"This part is white [c/FF0000:and this part is red]"` it is displayed as plain text
Here's an example in game
![image](https://user-images.githubusercontent.com/82264356/194040771-6b3a0cf2-fc3a-4c3c-b202-bb4bb00679a8.png)

**Comment by Setnour6** [comment]
The same thing has happened to me on my first mod back in tModLoader 1.3, where I tried to colour the buff tooltip but to no success. You can try utilizing Language.GetTextValue("Mods.YourModName.BuffTooltips") or something like that, provided that you are using Terraria.Localizations; and using a localization file (I like using hjson files)
I cannot say that it will work though, because I haven't tried that before with buffs, only with items.

**Comment by steviegt6** [comment]
> The same thing has happened to me on my first mod back in tModLoader 1.3, where I tried to colour the buff tooltip but to no success. You can try utilizing Language.GetTextValue("Mods.YourModName.BuffTooltips") or something like that, provided that you are using Terraria.Localizations; and using a localization file (I like using hjson files) I cannot say that it will work though, because I haven't tried that before with buffs, only with items.

This isn't a bug or anything, and using LocalizedText values changes nothing. This is a feature request.

**Comment by Setnour6** [comment]
> This isn't a bug or anything, and using LocalizedText values changes nothing. This is a feature request.

Thank you for correcting me, Stevie
