### ISSUE TITLE
tModLoader frequent crashing with the Windows 11 22H2 update.

### ISSUE THREAD

**Issue by JustRayy** [bluemagic123/tModLoader#3022]
### Version

Latest 1.3

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The game crashes after like 2-5 minutes of playing with the Windows 11 22H2 update, this didn't happen before but with this update cannot play Calamity ;-;-;-;

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9740033/client.log)

### Steps to reproduce

1. Have Windows 11 22H2
2. Open ModLoader
3. Join a friends world (haven't tested singleplayer)
4. Play
5. 2-5 minutes later it crashes.

### Expected Behavior

No crashes.

### Actual Behavior

A crash

### Reproduction frequency

Game has crashed 10 times today.

**Comment by Solxanich** [comment]
Looks like this is an error also reported on Terraria versions 1.4.4.3 and earlier. 
https://forums.terraria.org/index.php?threads/game-constantly-crashing-either-randomly-or-on-save-and-exit.112235/

An incompatibility with Win11 22H2 seems to exist. 
@Chicken-Bones  - thoughts? This seems fixed in 1.4.4.4 of Terraria, not sure if it is an easy item to toss back to 1.3 alongside the final 1.4.4.X GoG hashes.

**Comment by Chicken-Bones** [comment]
Workaround is to replace `File.Copy` calls with:
```cs
				try
				{
					File.Copy(source, destination, overwrite);
				}
				catch (IOException ex)
				{
					if (ex.GetType() != typeof(IOException))
						throw;

					// fallback for random File.Copy failures on Win11
					using (var inputstream = File.OpenRead(source))
						using (var outputstream = File.Create(destination))
							inputstream.CopyTo(outputstream);
				}
				return;

**Comment by JavidPack** [comment]
I've updated 1.3 with the workaround code, but there won't be a 1.3 release until Terraria 1.4.4 finishes up hotfixes.
