### ISSUE TITLE
Не запускается tmodloader

### ISSUE THREAD

**Issue by ManGo463** [bluemagic123/tModLoader#3024]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

![65P2ZmnSOVE](https://user-images.githubusercontent.com/115426679/194776663-431882cc-d06f-43c1-aebe-242e211309e9.jpg)
This error appears.
I tried to play modloader on version 1.4. The vanilla game runs without problems, modloader with version 1.3 of the game, too.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9742454/client.log)

### Steps to reproduce

Just trying to run the game

### Expected Behavior

Starting the game

### Actual Behavior

An error window appears

### Reproduction frequency

Every time there is a launch

**Comment by JavidPack** [comment]
I can't read what that says, but I think deleting the dotnet folder might help, give that a try: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#launch-issues

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
