### ISSUE TITLE
[1.4.4] Tiles_650 asset incorrectly capitalized as TIles_650

### ISSUE THREAD

**Issue by Rijam** [bluemagic123/tModLoader#3025]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The asset name for tile 650 (Rubblemaker 1x1 tiles) is incorrectly capitalized as `TIles_650`. This issue is just a reminder that this asset will need to be fixed in tModLoader once it reaches 1.4.4.

https://github.com/tModLoader/tModLoader/blob/a10475f1423c92cd556627e3a84ff8fbc3cc1b0b/patches/tModLoader/Terraria/ModLoader/Engine/TMLContentManager.cs#L97

**Comment by chlorine-dev** [comment]
It appears that the file still has the wrong name as of tModLoader v2023.11.3.3  and Terraria v1.4.4.9, Steam Windows version run via proton on Ubuntu Linux. As described in this issue it was named TIles_650.xnb instead of Tiles_650.xnb, which caused a game crash when trying to use the rubblemaker. Manually renaming the file fixed this issue.
