### ISSUE TITLE
Dotnet files can't loads

### ISSUE THREAD

**Issue by PlaushStig** [bluemagic123/tModLoader#3028]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

I downloaded tModLoader a week ago and it worked fine, but I decided to down
![Screenshot_381](https://user-images.githubusercontent.com/115511307/194968724-5b605b5d-bd8d-4e0a-b530-097fb5f259dc.png)
load it again, but I got this error

### Log File

[Launch.log](https://github.com/tModLoader/tModLoader/files/9749830/Launch.log)

### Steps to reproduce

1. Download tModLoader.zip
2. I transfer it to the folder with the game
3. I'm launching start-tModLoader

**Comment by JavidPack** [comment]
Try the suggestions in https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#launch-issues

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
