### ISSUE TITLE
Seemingly Random Crashing - Log doesn't seem to indicate any particular mod

### ISSUE THREAD

**Issue by oliverrook** [bluemagic123/tModLoader#3034]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Seemingly random crashing whenever GUI elements change or are interacted with.
No indication in log what mod could be causing it, or if it's a problem with tmodloader.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9788738/client.log)

### Steps to reproduce

Unsure, as it seems to happen randomly.
Known steps:
1. Open Tmodloader
2. Change mod loadout at least twice
3. Try to change something in the modpack menu

Or
1. Open Tmodloader with calamity installed
2. Beat wall of flesh
3. Use the Demon Heart

### Expected Behavior

Should be able to play without crashing upon using the Demon Heart

OR

Should be able to change around mods and mod packs without crashing.

### Actual Behavior

Causes crashes, though these are not the only instances.

### Reproduction frequency

Seemingly random, though about 1 every 2-4 times.

### Additional Information

I am using several lighting and graphical mods, including Fancy Lighting, Atmospheric Torches, and Lights and Shadows.

**Comment by JavidPack** [comment]
You may have to narrow down this issue further for us to be able to figure anything out. See if you can narrow down the issue to 1 or 2 mods through testing: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#flowchart

If you can, let us know the mods and exact replication steps.

**Comment by JavidPack** [comment]
Actually, sorry, this would be much better to work through on Discord:

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
