### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kaposha4** [bluemagic123/tModLoader#3062]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

It crashes very strangely, the game starts normally with an internal INTEL video card, and with NVIDIA it gives an error Failed to load asset: "Fonts\Item_Stack". Can anyone suggest what could be the problem?

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9889522/client.log)

### Steps to reproduce

Just start the game

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
