### ISSUE TITLE
Nurse Wont respawn

### ISSUE THREAD

**Issue by OhhmyDayss** [bluemagic123/tModLoader#3087]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

my Nurse wont respawn on my terraria world and when i started another world you didnt spawn

**Comment by JavidPack** [comment]
This sounds like a support question related to specific mods you are using.

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
