### ISSUE TITLE
it says please ensure steam is logged in and running but i have done everything and its not working 

### ISSUE THREAD

**Issue by ZakerSamoray** [bluemagic123/tModLoader#3102]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

I put tModLoader file next to the terraria file then when I start tModLoader it it extracts whatever file it needs then it says please ensure steam is logged in and running
![image](https://user-images.githubusercontent.com/113450737/203327132-154770f0-8abc-49b7-b2e2-b2f9f748c21d.png)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10067763/client.log)

### Steps to reproduce

i put the file next to terraria
start the tModLoader
it gives me the error

### Expected Behavior

opening tModLoader

### Actual Behavior

giving me an error

### Reproduction frequency

everytime

**Comment by JavidPack** [comment]
Somehow you have the steam_api.dll file despite owning the GOG version of the game, I would just completely reinstall Terraria and tModLoader, make sure to follow the install instructions exactly for GOG.

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
