### ISSUE TITLE
Não conseguir entrar no tmodloader de jeito algum, estou tendo o exato problema que eu achei meste vídeo: https://youtu.be/h1UcXTh8TVE

### ISSUE THREAD

**Issue by Ocoelhodoalem** [bluemagic123/tModLoader#3106]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

**Comment by cozykoko** [comment]
Can't get into tmodloader at all is all the information that was given. send some logs

**Comment by Benioteniso** [comment]
Cara, seria necessário você mandar mais informações sobre o problema.
Se puder editar o seu problema para dar mais informações, ajudaria.

**Comment by Ocoelhodoalem** [comment]
> Não consigo entrar no tmodloader é toda a informação que foi dada. envie alguns logs

Aqui está um vídeo que encontrei no youtube que esta sofrendo do mesmo problema que eu: https://youtu.be/h1UcXTh8TVE 
Se souber como resolver por favor me ajude ;-;

**Comment by Ocoelhodoalem** [comment]
> Cara, seria necessário você mandar mais informações sobre o problema. Se puder editar o seu problema para dar mais informações, ajudaria.

Aqui está um vídeo que encontrei no youtube que esta sofrendo do mesmo problema que eu: https://youtu.be/h1UcXTh8TVE 
Se souber como resolver por favor me ajude ;-;

**Comment by JavidPack** [comment]
(You should not be on 1.4-preview, switch back to Stable/None in the betas menu)

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
