### ISSUE TITLE
Title image reverts to default "Terraria" when dragging the planets in the loading screen

### ISSUE THREAD

**Issue by calebchervenka** [bluemagic123/tModLoader#3112]
### Version

Latest 1.4-stable

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Normally, the TML logo overrides the "Terraria" title screen header. While a loading screen is visible (loading mods at application start), there is a sun and moon that rotate across the sky which you can click and drag around. When you drag the planet around, the title reverts back to "Terraria" instead of the "tModLoader" image.

### Steps to reproduce

1. Open Terraria with any number of mods loaded.
2. Wait until the sun or moon comes into view
3. Drag the planet anywhere
4. The title resets

### Expected Behavior

The title should be staying as "tModLoader"

### Actual Behavior

The title reverts back to "Terraria"

### Reproduction frequency

100% of the time.

**Comment by MacaylaMarvelous81** [comment]
I think this is intentional since it switches to the old menu theme when you drag the planet.

**Comment by JavidPack** [comment]
Intended, yes

**Comment by Kanarisky** [comment]
It is very frustrating how the theme reverts like this, because naturally when you go to click Single Player after coming out of a world, the celestial body will be behind the button. I don't know if you meant this easter egg is intended by Redigit or by TML team, but it's not good either way. It also only happens the first time I click the UI in front of the bodies each session. Doesn't happen after that no matter how much I click them.

Could you please not revert the theme automatically when they're dragged? It seems pointless and trolly if that's the intended effect. Makes me not want to use modded menu themes at all if I have to re-select them every time.

**Comment by JavidPack** [comment]
Ok, I didn't realize the extent to which the easter egg affected other menus. It will now only affect the Terraria logo menu style to match the Terraria behavior. (This change will be live in Jan unless it is brought into the Dec release.)

**Comment by Kanarisky** [comment]
Thank you and sorry for being harsh in my comment. I had been annoyed about it for a while and finally found the cause, so I was a bit passionate.
