### ISSUE TITLE
Example Mod fails to load in game

### ISSUE THREAD

**Issue by Aceplante** [bluemagic123/tModLoader#3116]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Title. I wanted to see the changes in action, but it did not load

### Expected Behavior

To import the mod and have it work

### Actual Behavior

did not load with over 2k errors

**Comment by direwolf420** [comment]
Where did you get the ExampleMod? the correct one for 1.4-stable is this one: https://github.com/tModLoader/tModLoader/tree/1.4-stable/ExampleMod
To download ExampleMod source code to your computer rather than view online, download https://github.com/tModLoader/tModLoader/archive/refs/heads/1.4-stable.zip and then find the ExampleMod folder within

**Comment by Aceplante** [comment]
> https://github.com/tModLoader/tModLoader/tree/1.4-stable/ExampleMod
Yes, I downloaded that and put it in game, but it failed to build

**Comment by Chicken-Bones** [comment]
You have given us no info with which to help you with. ExampleMod definitely works for other people, so I don't know what you're doing wrong. This issue tracker is for bugs with tML, please try the Discord if you need support, but you will need to show people what you're doing and what errors you're getting.
