### ISSUE TITLE
Сant launch any version of Tmodloader

### ISSUE THREAD

**Issue by miaw228** [bluemagic123/tModLoader#3125]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

when I launch the console, it tells me "It has been detected that your installation directory contains third-party library files
that could potentially break tModLoader. If you have previously installed other tModLoader editions
- we recommend you to redownload them and install them into a folder separate from tModLoader\'s.
For example: 'steamapps/common/tModLoader64bit' (placed next to the 'Terraria' directory.)" I press enter, and then writes "Could not find the asset 'Wave Bank.xwb' " and every time tmodloader deletes Wave Bank

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10175299/client.log)

**Comment by JavidPack** [comment]
Well, log says it can't find D:\zhopa\Terraria\Content\Wave Bank.xwb, are you sure you fully installed Terraria?

The launch script saying that means you installed extra stuff previously, I would just reinstall both tmod and terraria after clearing out both install folders if it were me.

Also, you aren't supposed to install tmodloader into the same folder as Terraria, read the install instructions again.

I'll be closing this, since we don't provide support here:

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
