### ISSUE TITLE
Could not find file wavebank.xwb

### ISSUE THREAD

**Issue by NICKISBAD** [bluemagic123/tModLoader#3142]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When launched using steam it displays "Could not find wavebank.xwb" but terraria regularly works fine

**Comment by JavidPack** [comment]
Without a client.log, there is nothing we can do to help. Sounds like you just have things installed incorrectly, or tmodloader is looking in the wrong folder.

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
