### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by chertbec** [bluemagic123/tModLoader#3143]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

![H_DF5IkzaJk](https://user-images.githubusercontent.com/120937987/208300348-72c7d3dc-0328-46e0-98f5-6701a1d776a2.jpg)

**Comment by avdkmv** [comment]
please do not create a ticket without info
firstly, check the log file mentoined in the error - everything is described in detail in it 
if you can not solve the problem or find a solution - attach it to the ticket

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
