### ISSUE TITLE
у меня стим запущин и есть аккаунт почему? не запускается

### ISSUE THREAD

**Issue by Artyomcustov** [bluemagic123/tModLoader#3220]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
