### ISSUE TITLE
Ubuntu 22.04 LTS tmodloader no audio hardware found, Disabling sound

### ISSUE THREAD

**Issue by DunklerLT** [bluemagic123/tModLoader#3227]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Hello every time I start TMODLOADER it doesn't give me sound audio it says it can't find any device

### Log File

Hello every time I start TMODLOADER it doesn't give me sound audio it says it can't find any device

### Expected Behavior

Hello every time I start TMODLOADER it doesn't give me sound audio it says it can't find any device

### Actual Behavior

Hello every time I start TMODLOADER it doesn't give me sound audio it says it can't find any device

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.

When you do, make sure to post the client.log file
