### ISSUE TITLE
 it doesn't want to open my tmodloader

### ISSUE THREAD

**Issue by Freder777** [bluemagic123/tModLoader#3233]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

I have been trying for a long time to open my tmodloader but I get a very strange error. I tried to find a solution but I couldn't hopefully you can help me
![Captura](https://user-images.githubusercontent.com/124429026/216757529-0fd9d718-2da7-489f-9043-6458815984f0.PNG)

### Additional Information

windows is 7

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
