### ISSUE TITLE
Multiple HJSON Files for Catagorized Localization Entries

### ISSUE THREAD

**Issue by lace-wing** [bluemagic123/tModLoader#3241]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Currently 1.4.4 tModLoader will populate all localization entries which it will automatically read (Items, Buffs, Projectiles etc.) into a single `.hjson` file, instead of putting them into existing, manually set `.hjson` files. Here's an example: 
```
Localization/
  Weapons/
    en-US.hjson
  Tools/
    en-US.hjson
  Foods/
    en-US.hjson
```
A food item `MyFood` has an entry in `Localization/Foods/en-US.hjson`.  
```
Items: 
  {
    MyFood: {...}
  }
```
While a weapon item `MyWeapon` has an entry in `Localization/Weapons/en-US.hjson`.  
```
Items: 
  {
    MyWeapon: {...}
  }
```
After reloading the mod, the weapon item's entry is generated in `Foods/en-US.hjson` instead of using the existing entry in `Weapons/en-US.hjson`.  
```
Items: 
  {
    MyFood: {...}
    MyWeapon: {...}
  }
```
This prevents modders from separating the `.hjson` files. There's no problem for small mods, but for mods which have like 50 weapons, 10 tools, 50 accessories, 30 foods and 20 drinks (can be even more), it's a considerable issue. 

My proposal is to fix this to allow usage of multiple language files catagorized localization entries. 

### What does this proposal attempt to solve or improve?

It'll enable modders to manage their bunches of localization entries under the same catagory (example, `Items`), improve readability and make translators life easier. 

### Which (other) solutions should be considered?

Alt solution 1:  
Modders can override the `LocalizedText` properties and use inheritances to retrieve translations from their custom keys, but that is a lot of effort when dealing with a huge amount of texts.

Alt solution 2:  
Add methods to allow modders to change the way tModLoader retrieve translations for existing, catagorized `ModType` in a certain context. For example, an imaginary method `ModifyLocalizationKey(LocCatagory.Items, "Content/Items/Weapons", "Mods.MyMod.Items.Weapons")` will make tModLoader retrieve `DisplayName`, `Tooltip` and other `LocalizedText` properties of `ModItem`s under `Content/Items/Weapon` from `Mods.MyMod.Items.Weapons` instead of `Mods.MyMod.Items` by default.

**Comment by JavidPack** [comment]
Can you please upload this test mod as a zip? I believe this was working before, so I'll need to test with your example.

**Comment by lace-wing** [comment]
> Can you please upload this test mod as a zip? I believe this was working before, so I'll need to test with your example.

This issue gets weird. The `.hjson` files are correctly updated on my pc, but not on some of my friends'. One thing in common is that tModPorter doesn't work on their pc too.

**Comment by lyc-Lacewing** [comment]
[TestHjson-before.zip](https://github.com/tModLoader/tModLoader/files/10661816/TestHjson-before.zip)
The test mod

**Comment by lace-wing** [comment]
[TestHjson.zip](https://github.com/tModLoader/tModLoader/files/10661863/TestHjson.zip)
The test mod

**Comment by JavidPack** [comment]
Seems to be working for me. Since the food and items hjson files both have the Mods.TestHjson.Items prefix existing for an existing key, the game will have to choose one of them to add the new entry for a new item just added. Which file is updated is probably determined by filename in some way, but this is an intended behavior. The intention is the modders would separate hjson files such that unique key prefixes are only present in one of the files, if they want the placement of a new key to be consistent. 

Unless you make the keys unique, this manner of splitting hjson files won't be useful for you.

**Comment by Chicken-Bones** [comment]
To clarify what @JavidPack said. There is no way to tell that a new item is a food/weapon/tool as per your arbitrary categorisation, so we cannot automatically assign new keys to the 'right' file.

We do currently support separate files for all with a common prefix. `Mods.ModName.Items` vs `Mods.ModName.Projectiles` for eg. tModLoader will detect an existing file containing `Mods.ModName.Items` keys to add new items to, etc.

Please note that while you may feel that splitting your localizations into many little files helps with organization, we do not recommend it, as it is generally easier for everyone to just Ctrl+F in a single localization file, rather than having to find the relevant one when a piece of content is added or a localization needs changing.

**Comment by Setnour6** [comment]
I decided to take the initiative and make adjustments to the contents in the zip file.
I added an "ExtraTest" folder, followed by "ExtraContent", and added the same exact folders that were in the main mod source folder directory (being the name of the mod). The only difference is that I made adjustments to the duplicated content to make it unique with it's own localization file.
[TestHjson.zip](https://github.com/tModLoader/tModLoader/files/10669298/TestHjson.zip)
Note that you will get an error when loading the test mod. That is intentional. The way the "ExtraContent" localization file is shown is intentional.
I do not want to have to use a long file name, let alone use `Mods.TestHjson` in the file name in the "ExtraTest/ExtraContent" folders, but I still want to have the localized content load.

If another "ExtraContent" folder were to be made, titled "BonusContent", with all of the content from the original "ExtraContent" folder... Things from the "BonusContent" folder would be added to the "BonusContent" localization file.

Alt Solution 2 is considered mostly for this comment
