### ISSUE TITLE
TModLoader won't install and i have no idea why.

### ISSUE THREAD

**Issue by WelcomeToMyParentsHouse** [bluemagic123/tModLoader#3249]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I just discovered this mod about a month ago and wanted to get into it. But when I tried to install it it would show a popup of "Preparing to launch TModLoader" for half a second and then vanish. vie tried disabling my antivirus and firewall, nothing happened. Tried restarting steam, nothing happened. and a I tried restarting my PC and still nothing changed! I'm not trying to sound overly dramatic or anything but it's just frustrating and I would like to know what is happening. i really don't want to have to uninstall terraria and reinstall it but if I have to then I will.

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
