### ISSUE TITLE
Modded prefixes should persist through mod unload

### ISSUE THREAD

**Issue by ScalarVector1** [bluemagic123/tModLoader#3250]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

I am proposing a placeholder prefix, similar to the placeholder items and tiles in TModLoader so that modded prefixes can persist on items through reloading, similar to how modded items or tiles do. 

I can see 3 ways in which this is presented to the end user:

1) The item keeps the name of the modded prefix, but the prefix tooltip is changed to something along the lines of 'no effect, re-enable [Mod that the prefix came from] to use this prefix'

2) The item's prefix is displayed as "Unloaded prefix", and has no tooltip

3) The item appears to the player as if it has no prefix, but will re-gain its previous prefix if the mod adding it is loaded again

### What does this proposal attempt to solve or improve?

Currently, if a player reforges an item and gets a prefix from a mod, then proceeds to unload the mod that gave the prefix but not the item, and load their player, the prefix will disappear. This can be irritating for players who invested resources into obtaining a specific prefix only to have it deleted by the game.

**Comment by Chicken-Bones** [comment]
Given that every `Item` has an `UnloadedGlobalItem` component (regardless of if the item has any unloaded data on it).
1. Make an `UnloadedPrefix : ModPrefix` in tML, localize it.
2. Add an `unloadedPrefix` field to `UnloadedGlobalItem`, add to `SaveData`
3. Only save the `unloadedPrefix`, if `Item.prefix` is `UnloadedPrefix` (so the data gets ignored if the item changes prefix).
4. Adjust `ItemIO.Load` to set the `unloadedPrefix` field when the `ModContent.TryFind` call fails on `"modPrefix..."`
5. Move the above code into an internal `ItemIO.LoadModdedPrefix` method.
6. Adjust `UnloadedGlobalItem.LoadData` to call `ItemIO.LoadModdedPrefix` if there's an `unloadedPrefix`.
7. (Optional) use `GlobalItem.ModifyTooltips` to show details about the unloaded prefix

**Comment by direwolf420** [comment]
I would prefer if the prefix would not actually have a name, and only displayed some text (in green or red like the usual prefix colors for stats) that it's unloaded and that its actual prefix is "modname/prefixname". (For the purposes of `Lang.prefix` use by mods it should still have one, it just shouldn't be displayed in the relevant gameplay locations imo)

The reason for that is that item names become pretty silly ("Unloaded Prefix Megashark"), and it would also display as such in kill messages in pvp. Also, the prefix has no functional use.
The downside of not having a name however is that the player may think it has no prefix at all and accidently reforges it. But this situation should come up rarely since mod disabling is only done to troubleshoot or to get rid of a mod for the rest of a playthrough so the loss of the prefix doesn't hurt.

As a reference, a mod already implement this: https://steamcommunity.com/sharedfiles/filedetails/?id=3049076805
