### ISSUE TITLE
About damage display and damage resistance

### ISSUE THREAD

**Issue by ReishyouSose** [bluemagic123/tModLoader#3356]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Can add a hook for whether to damage display and adjust its color among the various Strike hooks?
----- bool CombatText(ref Color color)
And a means of complete defense against damage @prehurt =>false
![QQ图片20230328232746](https://user-images.githubusercontent.com/103470030/228288738-30c128fa-7007-408c-a1cc-0dfa4511b379.png)

### What does this proposal attempt to solve or improve?

On_strike is too troublesome

### Which (other) solutions should be considered?

Move the dodge hook after the ModifyHit hook?

**Comment by Chicken-Bones** [comment]
Yes, we could add a method do hide the combat text, in `Player.HurtModifiers` and `HurtInfo`, similar to NPCs.

As for dealing 0 damage, what's wrong with the `ImmuneTo`? I assume you want to do something like 'Player ignores damage below a certain amount' rather than just taking 1 damage like vanilla (which works fine, life-regen exists, you can also just counter-heal the player).

It looks like, for _player_ hooks specifically, it would be possible to cancel the strike right before it is applied. Something like `CanHurt(HurtInfo)`.

Please provide the reason (with 1.4 code) for why you want this feature

**Comment by Chicken-Bones** [comment]
After discussion with the team, the request to move dodge hooks after `ModifyHurt` hooks seems reasonable and achievable. I'd still like to hear your use-case.

**Comment by Chicken-Bones** [comment]
See #3359

**Comment by ReishyouSose** [comment]
Wmmmm, mainly because of the need to:
Decide whether to dodge or not based on the value of the damage to be taken.
I think the new change fixes that (I've seen you guys move the dodge hook to be called after modifyhurt)
But I can't test it due to a full class in the morning, so I'll do that this afternoon and follow up with a reply

**Comment by ReishyouSose** [comment]
Problem solved, looking forward to the CanHurt hook，thanks

**Comment by Chicken-Bones** [comment]
> Problem solved, looking forward to the CanHurt hook，thanks

`CanHurt` is not required, `FreeDodge` does everything it would do now

**Comment by ReishyouSose** [comment]
Well,that's right
