### ISSUE TITLE
Restore allowFallbackToStyleZero option in GetItemDropFromTypeAndStyle

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#3398]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

In #3210, GetItemDropFromTypeAndStyle at one point had an optional allowFallbackToStyleZero parameter to control the behavior of falling back to style 0 if a specific style was not found, it was removed since it didn't have a use (https://github.com/tModLoader/tModLoader/pull/3210/commits/0e0cfac0f76d5f6612a944918e77fb06b4d6f3a4)

Direwolf420 brings up that banner tiles could use this for styles that used to exist but have been removed but the sprite is unchanged. For example, an enemy was removed from a mod. Direwolf420 wants 0 to return if the style isn't found, rather than the style 0 item entry. This use case makes sense.

Adding the parameter back in is simple enough, but I am unsure if `allowFallbackToStyleZero` should still default to true. It is used in ModTile.GetItemDrops. When making the PR, I imagined there might be tiles that might change to styles not represented by an item.placestyle, and should still return the original item, so falling back was safest, but I can't think of any examples at the moment. 

So the question is: Are there any situations where `allowFallbackToStyleZero` should ever actually be used? If the default is true, then tiles with styles no longer used will return the style 0 item by default, so modders will need to override GetItemDrops. If the default is false, then there is potentially situations where modders will need to override GetItemDrops, but I can't think of them at this time. I think most tiles that change in some way, usually keep the style and just change, but that might not be the case.

**Comment by Chicken-Bones** [comment]
I thought the primary use of the fallback would be for mods where items allowed placing specific variants, but otherwise had a 'default' drop. The secondary use was dropping the 'normal' variant of an item in case of style corruption.

Given feedback by @Ozzatron and @direwolf420 it seems that no drop is preferred in case of corruption.

There is also no way for mods to register a `(type, style) -> item` entry manually for their styles, so maybe we could add that as a way to give some easy control over the simple lookup. 

I think that the fallback behaviour can be removed, since there's no guarantee that style 0 has a placeable item. Perhaps a 'FallbackItemDrop' parameter/method/property could be added instead?

@direwolf420 also suggested naming `ItemDrop` to `ItemDropOverride`, because otherwise people may think it is a fallback to the 'default' type+style lookup
