### ISSUE TITLE
TModloader 1.4 crashes on startup, no error message

### ISSUE THREAD

**Issue by basicallyjustnat** [bluemagic123/tModLoader#3468]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I start Tmodloader it displays the command prompt window, and then crash upon opening, sometimes not even loading the game in. Version 1.3 works perfectly fine, but 1.4 and 1.4.4 don't. I've tried hard uninstalling, verifying file integrity of Tmodloader and vanilla Terraria, reinstalling dotnet, but nothing works.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11434957/client.log)

**Comment by JavidPack** [comment]
There are some suggestions here: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#black-windows-appears-and-closes-but-nothing-else

Other than that: 
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
