### ISSUE TITLE
weird glitch that stops tmod loader from launching

### ISSUE THREAD

**Issue by hyperwilliam** [bluemagic123/tModLoader#3472]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

this error seems like another one black box launching and closing with no tmodloader and error but. the only way i can get it to work is tmodloader 1.3 that means softcore only so its annoying because i play in journey mode.

### Steps to reproduce

no idea

### Expected Behavior

black screen open and closing and then tmodloader opens

### Actual Behavior

black screen then both terreria and tmodloader open then black screen goes away and not opening

### Reproduction frequency

every time i launch tmod loader

### Additional Information

no idea

**Comment by hyperwilliam** [comment]
it for some reason put modding instead of player so dont get confused

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
