### ISSUE TITLE
Рушил скачать tModLoader но вылетает ошибка failed to "download dotnet-install.ps1. relying on powershell to work"

### ISSUE THREAD

**Issue by Wertanio** [bluemagic123/tModLoader#3473]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

при включение тмода оно выдает ошибку failed to download dotnet-install.ps1. relying on powershell to work не понимаю что делать
спасибо если поможете

### Steps to reproduce

запустить тмод
ждать чёрный экран с кодом(хз честно у меня так)
увидеть failed to download dotnet-install.ps1. relying on powershell to work
выключение приложения

### Expected Behavior

спокойный запуск

### Actual Behavior

не запускается

### Reproduction frequency

всегда

### Additional Information

нету

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
