### ISSUE TITLE
Allow GoG tML installation in Applications folder on OSX

### ISSUE THREAD

**Issue by Chicken-Bones** [bluemagic123/tModLoader#3526]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

See recent confusion at the end of #3093, no reason not to support yet another install location for GoG users. 

### What does this proposal attempt to solve or improve?

They tend to have trouble getting tML into a spot where it can find Terraria.

### Which (other) solutions should be considered?

Make better instructions for Mac GoG users

**Comment by JavidPack** [comment]
`~/Library/Application support/Terraria` is the Terraria saves directory. tModLoader saves to `~/Library/Application support/Terraria/tModLoader/`.

Steam Terraria installs to `Library/Application Support/Steam/steamapps/common/Terraria/` and tModLoader to `Library/Application Support/Steam/steamapps/common/tModLoader/`

According to GOG, they install games to `~/Applications` (https://docs.gog.com/bc-installation-dir/)

We should update https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation to a link to or include the same information as https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#install, and update that with the Mac GOG location.

We we don't want to do is tell people to install the game into the saves directory, which is hard since the saves directory and the steam install directory both start with ``Library/Application Support/`

**Comment by Chicken-Bones** [comment]
One thing to note is that Mac is even more heavily UI based than windows, so video or image tutorials are almost certainly required for users to be able to distinguish directories. I'm happy with just an instruction update. Reassigning to you
