### ISSUE TITLE
SELinux Alert tModLoader gives exec permissions to heap memory

### ISSUE THREAD

**Issue by sirfredrick** [bluemagic123/tModLoader#3534]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I run tModLoader on Fedora Linux with SELinux enabled an alert dialog pops up.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11714715/client.log)

### Steps to reproduce

1. Install Fedora Linux 38
2. Make sure SELinux is set to enforcing (run `sestatus` and look for `Current Mode: enforcing`
3. Install `steam` from [RPM Fusion repos](https://rpmfusion.org/Configuration)
4. Install `dotnet` from Fedora repos
5. Launch Steam and install Terraria and tModLoader
6. Launch tModLoader with or without any mods installed
7. See game loading successfully but an SELinux alert dialog pops up

### Expected Behavior

You should not be giving exec permissions to heap memory on Linux as this is dangerous.

### Actual Behavior

SELinux is detecting that exec permissions are being given to heap memory on startup. The alert dialog says that the process `dotnet` is attempting to access `execheap`.

### Reproduction frequency

I am able to reproduce this with every launch of tModLoader.

### Additional Information

Fedora Linux 38
Linux kernel 6.3.6
Mesa Intel UHD Graphics 620 23.1.1
KDE Plasma 5.27.5
dotnet 6.0.116
Terraria 1.4.3.6
tModLoader 2022.9.47.50
![selinux_dialog](https://github.com/tModLoader/tModLoader/assets/23219582/a5e97fb9-aebb-4f24-a452-4a66045ae7b0)
![selinux_alert_browser](https://github.com/tModLoader/tModLoader/assets/23219582/00da7a5e-a949-4701-950e-29b8e1db6f33)

**Comment by LittleJay1985** [comment]
It's due to TModLoaders necessary use of MonoMod.

TModLoader loads mods by effectively modifying the main assembly in memory and injecting the mods. It needs to make some pages of memory executable for the Jit compiler to run the injected code.

It's nothing to worry about as it is just a SELinux 'Warning' not a 'Never Allow' 


As taken from https://fedoraproject.org/wiki/SELinux/Unsound_or_dangerous_SELinux_policy_practices#Warnings

_**Warnings**
The following part describes policy elements that usually indicate issues in component or policy module design and are generally not advisable to use. However, there are (rare) cases where they are needed to ensure proper functionality.
....
Execheap / execmem / execstack / execmod - (mapping memory that is both writable and executable)
Only necessary for JIT compilers and similar_

Hope that helps.

**Comment by Chicken-Bones** [comment]
@LittleJay1985 is correct. In normal circumstances, a process attempting to edit its own executable memory (program code) can be indication of a malicious exploit. 

In the case of tModLoader, mods which alter the vanilla Terraria code require re-writing the program during operation, hence the warning. This functionality is provided by `MonoMod`.
