### ISSUE TITLE
World autosave problem

### ISSUE THREAD

**Issue by mjhabdm** [bluemagic123/tModLoader#3536]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

World autosave problem.
The problem appeared suddenly, played with such mods. Calamity, Magic Storage, Unnofficial Calamity Whips, better Zoom, Helpful Hotkeys, Sleep Time Adjustment, player location saving, Terraria Overhaul, Summoners Association. I never had any problems, I reached almost the end of the game, but suddenly the world stopped saving. How can I fix this or is it no longer possible?

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
