### ISSUE TITLE
"genGore = false;" Doesn't Disable Player Gore

### ISSUE THREAD

**Issue by Symtaro** [bluemagic123/tModLoader#3658]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

In the PreKill() hook (inside the ModPlayer class), if you set the genGore parameter to false, the game still generates player gore on death. Of course, if you set it to true, the game generates the player gore as well, leading me to think this is a bug.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12156101/client.log)

### Steps to reproduce

1. Set the genGore parameter to false in the PreKill() hook.
2. Build the mod and load into a world.
3. Die and notice the player gore still generates.

### Expected Behavior

"Set the genGore parameter to false to stop the gore and dust from being created." -tModLoader: Classlist

### Actual Behavior

The player gore still generates on death.

### Reproduction frequency

100%

### Additional Information

Disabling other mods and resource packs doesn't solve this issue.

Another modder had the same issue with the playSound parameter (the game would still play the death sound on death). I think the solution for that could be helpful here.
Here's the link to that issue: https://github.com/tModLoader/tModLoader/issues/3554

**Comment by JavidPack** [comment]
Ok I did some testing, it seems since tModLoader was created this parameter has had a misleading name. The parameter doesn't stop gore, it stops the dust, technically. Technically when a player dies, the player doesn't even spawn "Gore", it's just the player parts being rendered at different places. It does spawn "Dust" that looks like blood, so maybe the parameter name isn't really wrong.

![image](https://github.com/tModLoader/tModLoader/assets/4522492/61395ca4-b73c-4a84-8020-682a5d2c539a)

Basically, the parameter controls the blood, not the body parts. This is used in vanilla to swap out blood for ice dust when wearing the Frost armor set. This is the intention of the parameter, for modders to supply their own dust and bypass the existing dust.

If you need a way to stop the body parts I think setting `Player.headPosition/bodyPosition/legPosition` to something really far offscreen, like (-100000, -100000), in `ModPlayer.Kill` while `player.dead` would probably work.

I'll update the docs to make it more clear.

**Comment by Symtaro** [comment]
Thank you very much for your insight! I’ll take your advice.

**Comment by Symtaro** [comment]
Would it be better to instead make the player invisible while they're dead?
Is something like that even possible? I noticed the DrawLayers hooks, but
I'm skeptical if that would even work.

**Comment by JavidPack** [comment]
That could probably work too.
