### ISSUE TITLE
Unable to get Touhou menu updated

### ISSUE THREAD

**Issue by wabisobby** [bluemagic123/tModLoader#3700]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I simply cannot get it to update properly or navigate it to put it in the correct files. Pls help bruv

### Steps to reproduce

1.load game
2.try and press update under the pack in mods
3.struggle to find correct files
4.download all of them and try and input each one individually with it doing nothing still
5.attempt to gather new information
6.become upset with lack of information
7.try a few more times steps 1-6
8.make an account so you can create a forum post on the isssue

### Expected Behavior

the title screen gets a new title screen

### Actual Behavior

its not working at all

### Reproduction frequency

often

### Additional Information

please help

**Comment by JavidPack** [comment]
I'm not quite sure what you are asking. Is this a question about a specific mod? Are you trying to enable a mod, or are you making a mod?

If the issue is with a mod made by someone else, we can't help you with that, the author of that mod will need to fix that. I suggest contacting the author directly or comment in the workshop comments for that mod.

If you are trying to make a mod, that's what the Discord (https://tmodloader.net/discord) is for, we don't provide programming support here on the GitHub issue tracker, the issue tracker is for tModLoader development, not mod making questions.

**Comment by wabisobby** [comment]
Yikes man, bad day? Don’t take my question responses personally lol, and
you deleted the thread and now I know so we’re good right? I’m already
having issues just trying to update a mod texture and it won’t work, was
just looking for some helpful feedback. Didn’t know the forums were such
hot grounds, hope your day gets better!
-xela

**Comment by JavidPack** [comment]
I'm sorry if you felt like I was upset with you, I'm not and did not intend to come across that way. My intention was to just direct you to the correct place to get help with what you need.

**Comment by wabisobby** [comment]
Gotcha, sorry for the misinterpretation. I appreciate you taking the time
to clarify. Thank you
-xelA
