### ISSUE TITLE
Sync issues when joining server with custom built tmod file hard to diagnose

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#3704]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I was helping someone diagnose an issue. The client.log showed that the user loaded `InfernumMode v1.9.24` locally, but when connecting to the server, `Download queue: InfernumMode v1.9.24[e634adbb],` was seen in the log. Eventually we figured out that the server had a different build of the same mod with the same version number.

Better logging could help diagnose this issue more quickly. A message mentioning why a file ends up in the Download Queue would help. (Missing locally, older locally, hash mismatch)

It also might be useful not to allow downloading mods from the server when the local version is the workshop version, in that situation the server is usually out of date. At the very least maybe mods shouldn't downgrade versions if the server is older. We could reinstate behavior similar to `ModNet.onlyDownloadSignedMods` by assuming a local workshop copy is correct/official.

**Comment by Chicken-Bones** [comment]
Additional logging will help yes, but the primary fix is to make sure that workshop mod versions are prioritized over local versions when they're newer, unless the server explicitly wants the copy in the mod directory.

The intent is that you should be able to connect to an outdated server and continue your playthrough.
When playing single-player your game should probably use the latest version of the mod (that you now have from workshop).

There's a feature deficit where if you were to use that player in a single-player world on a newer mod version, it may break when loading the older mod version and returning to the server, so we should consider warnings and mitigations around this.

We should also warn users about downloading mods from servers regardless. The warning message would be a good place to put the version (or hash) differences. I don't think it makes sense to ban server downloading by default due to above mentioned playthrough continuity issues.

We'll have to ask mod developers how they prefer to manage mod versions during development. They may prefer not to bump the version number until they're ready to publish, to avoid accidental early publishing. We need to ensure they can still test their mods (and distribute test versions of their mods via hosting a server).

I was working on some of the backend for this in #2931

**Comment by JavidPack** [comment]
Mostly covered by https://github.com/tModLoader/tModLoader/pull/3822, but I'm committing additional logging as well so we can see this info in client.log.
