### ISSUE TITLE
Summon Tag Damage doesnt work

### ISSUE THREAD

**Issue by codebykoi** [bluemagic123/tModLoader#3721]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When using a whip, it doesnt add damage to summons.
doesnt even work without mods.
It works in vanilla tho.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12328723/client.log)

### Steps to reproduce

1. Get any whip in TModLoader
2. Get any summon
3. Strike some enemy with a whip and see how it doesnt adds damage to summon.

### Expected Behavior

Increased damage for summons from using whips

### Actual Behavior

The opposite

### Reproduction frequency

Every single time

### Additional Information

Someone made a post on steam with the same problem

https://steamcommunity.com/app/1281930/discussions/0/3821906878977525828/

**Comment by JavidPack** [comment]
I'm having trouble replicating this issue. I tested with slime staff, hoplite, and leather whip. I tested on the latest 1.4.4-stable tModLoader

As you can see, the slime deals 2 to 4 damage before the tag, then 6 to 8 after. Seems to be working.

https://github.com/tModLoader/tModLoader/assets/4522492/198acbff-79cb-42aa-b575-210f2adb90f3


Can you disable all mods and replicate your issue, and tell me the exact setup?

**Comment by codebykoi** [comment]
I tested the same thing with every single mode 1 by 1, and somehow i cant replicate the issue. But summon tag doesnt work in my world somehow.

**Comment by JavidPack** [comment]
Well, that complicates things. You might want to come to the discord for support, we won't get far going back and forth like this.

Some things you can try are enabling all your mods in a new world and enabling all your mods in a new world and new player, see if those work. If they do, then it seems like it might be an intentional choice by some mod, maybe the effect of some accessory or armor your original player was using. I didn't see any errors in your log file, so it doesn't seem like a bug.

**Comment by codebykoi** [comment]
I checked there is no configurations about summon damage or anything similar. I will move to discord for sure.

**Comment by JavidPack** [comment]
Did you figure this out?

**Comment by codebykoi** [comment]
Not yet, but i would assume its has something with the mods, i cant test rn cuz reinstalled my workflow, we can close it
