### ISSUE TITLE
ModifyWeaponDamage doesn't properly effect minions/sentries

### ISSUE THREAD

**Issue by BlockCrusader** [bluemagic123/tModLoader#3730]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When mods use the `ModifyWeaponDamage` hook/method, either in a `GlobalItem` or `ModPlayer` class, any modifications made are not applied to minions, sentries, or any other `Projectile` with `ContinuouslyUpdateDamageStats`

After looking at the decompiled source-code, I believe this is due to the fact that when a `Projectile` with `ContinuouslyUpdateDamageStats` updates its damage, `ModifyWeaponDamage` is never called.

### Log File

N/A (Didn't think this was needed since no errors/exceptions are being thrown here)

### Steps to reproduce

1. Find and activate a mod which has a feature that uses `ModifyWeaponDamage` to increase weapon damage. I have confirmed `ExampleMod` and its `WeaponWithGrowingDamage` `GlobalItem` recreates the bug
2. Obtain a summon weapon (Ideally one that can passively hit target dummies - like the Vampire Frog Staff - for ease of testing)
3. Use the mod's `ModifyWeaponDamage` utilizing feature to boost the summon weapon's damage
4. Notice that the minion's damage does NOT increase despite the damage boost, even after re-summoning. Larger boosts will be more noticeable

### Expected Behavior

The minion/sentry weapon gains modified damage from a mod's usage of `ModifyWeaponDamage` 

### Actual Behavior

Despite modifications - and the weapon's tooltip changing to match the new, expected damage - minion/sentry damage is not impacted by the mod's usage of `ModifyWeaponDamage` and deals the same damage dealt before applying the modifier

![dmgScalingBug](https://github.com/tModLoader/tModLoader/assets/141888765/bfdce3a2-2d93-4433-a5e6-162ea46f4e3f)

### Reproduction frequency

100%

### Additional Information

A possible solution would be to call `CombinedHooks.ModifyWeaponDamage` in the `OnSpawn` hook/method, saving the `StatModifier` that results, and changing the damage update code in `Projectile.Update` to integrate the saved `StatModifier` into the updated damage by using `CombineWith`

Some things to consider with this solution;
- `CombinedHooks.ModifyWeaponDamage` has an `Item` parameter, so a way to retrieve the `Projectile`'s parent `Item`, so a way to retrieve that `Item` via. `OnSpawn` 's given `IEntitySource` would have to be devised. From my experience, this can become very finicky if not impossible if the `Projectile` is a secondary or tertiary projectile, since such projectiles' `IEntitySource` is not directly the `EntitySource_ItemUse` we're looking for. Then again, I'm no master modder.
- Saving the `StatModifier` acquired from `CombinedHooks.ModifyWeaponDamage`; will this just have to be a `ModProjectile` variable of some sort? If so, modders probably shouldn't be able to change it, and I can't think of any possible use-cases for such a thing outside of this Issue.

**Comment by direwolf420** [comment]
It's a weird issue to tackle because modders can use ModifyWeaponDamage for a wide variety of things, like temporary buffs, or fixed buffs to make a weapon stronger after defeating bosses.
Doing it through OnSpawn once will snapshot those temporary buffs, which is not intended.
Updating it every tick is pretty much impossible for minions specifically since you swap away from the weapon most of the time (to a whip), you can't really hold an item reference in this game to call the hook on (i.e. you put it into a chest or drop it in the world, which is done through cloning).

**Comment by Chicken-Bones** [comment]
I'm wary of changing this because, as direwolf420 said, it depends how modders are using the hook. In theory it makes sense to capture the `StatModifier` from `ModifyWeaponDamage` and store it on the projectile, and pass it on to children, but that would end up making an already complicated system even more complicated.

The main risks are:
- Modders are using `ModifyWeaponDamage` for 'temporary' effects (stealth bonuses for eg)
- `originalDamage` is synced over the network, as it's expected to change over time for some projectiles.
- Projectiles which spawn children may be passing a value derived from `originalDamage` to the `damage` parameter of `NewProjectile`
- Certain vanilla projectiles would need updating because they manipulate `originalDamage` in specific ways. Abigal, Storm Tiger, and Stardust Dragon` are of note.

As a work-around, I recommend using `OnSpawn` and checking for `IEntitySource_WithStatsFromItem` to update `originalDamage`

**Comment by BlockCrusader** [comment]
Thanks for the insight and advice @direwolf420 and @Chicken-Bones. Would it best to go ahead and close this issue, then?
