### ISSUE TITLE
tModLoader v2022.9.47.85 Fatal Error

### ISSUE THREAD

**Issue by ElvisTek146** [bluemagic123/tModLoader#3732]
### Version

Latest 1.4.3-legacy

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When trying to start the tmodloader it gives me a fatal error

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12364457/client.log)

### Steps to reproduce

1. open steam
2. launch tmodloader
3. fatal error

### Expected Behavior

open tmodloader

### Actual Behavior

fatal error

### Reproduction frequency

allways

### Additional Information

I would appreciate your help with this problem.

**Comment by TTrongjit** [comment]
I also have the same issue this is my log file 
[client.log](https://github.com/tModLoader/tModLoader/files/12367488/client.log)

**Comment by Mangochicken13** [comment]
have either of you tried validating the tmodloader files in steam?

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
