### ISSUE TITLE
Potential security vulnerabilities

### ISSUE THREAD

**Issue by PassiveLemon** [bluemagic123/tModLoader#3763]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

My Docker image reports CVE vulnerabilities [2019-0820](https://scout.docker.com/vulnerabilities/id/CVE-2019-0820?utm_source=hub&utm_medium=ExternalLink) and [2018-8292](https://scout.docker.com/vulnerabilities/id/CVE-2018-8292?utm_source=hub&utm_medium=ExternalLink). Maybe these are something to look into?

Docker container is [here](https://hub.docker.com/layers/passivelemon/tmodloader1.4-docker/latest/images/sha256-961a056c47e44e701184dad64e6af0c387296e6976c18a0a5d59ac2bdad0b4dd?context=explore).

### What does this proposal attempt to solve or improve?

Potential security improvements to the server.

**Comment by Chicken-Bones** [comment]
I'd like to know what tool you used to get the reports, for my own curiosity. 

As for CVEs you'll be happy to know that tML lets you run untrusted code in the form of mods, which is like CVE 0001. I'd recommend not joining servers where you don't personally know/trust all the users if you're worried about a privacy breach.

**Comment by PassiveLemon** [comment]
I used Docker scout, a built in feature on Dockerhub that you have to enable for your repository

**Comment by steviegt6** [comment]
*Copy-pasted from my response in a discussion on Discord:*
These are non-issues:
- CVE-2019-0820 was patched in later versions of .NET Core (doesn't affect any major versions past .NET Core 2.2 afaik either)
- CVE-2018-8292 was patched back in the .NET Core 2.0 days as well...

Both of these are would only be exploitable when present in external (mod) code (not that it matters, since they've literally never had an impact on .NET 5+), in which a bad actor could easily distribute their own exploits anyway.

**Comment by Chicken-Bones** [comment]
these are non-issues:
- CVE-2019-0820 was patched in later versions of .NET Core (doesn't affect any major versions past .NET Core 2.2 afaik either)
- CVE-2018-8292 was patched back in the .NET Core 2.0 days as well...
both of these are would only be exploitable when present in external (mod) code (not that it matters, since they've literally never had an impact on .NET 5+), in which a bad actor could easily distribute their own exploits anyway
