### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by LittleLily07** [bluemagic123/tModLoader#3772]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

the game will not open

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12461577/client.log)

### Steps to reproduce

1. open game 

### Expected Behavior

the game should open normally 

### Actual Behavior

the console window will open for a few seconds then close with no error message or anything 

### Reproduction frequency

every time without fail

### Additional Information

I have no mods installed and have reinstalled both the tModloader and Terraria files a number of times 

unsure if it will be helpful but I have included the launch text file and the Natives text file from the tModLoader files 
[Natives.log](https://github.com/tModLoader/tModLoader/files/12461617/Natives.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/12461619/Launch.log)

**Comment by JavidPack** [comment]
Looks like your .net runtime install is broken, I would try uninstalling .net core (https://learn.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows#uninstall-net) from your computer and also deleting the dotnet folder in the tmodloader install directory. If you need further assistance please come to our Discord, the issue tracker is for tracking bugs, not support.

**Comment by Mononok0** [comment]
Version
Latest 1.4.4-stable

OS
Windows

**Platform**
Steam

**This bug affects**
Launching the game

**Description**
The game fails to launch, saying I have a corrupt config.json.
Replacing my config.json with the one found here ( https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#configjson-corrupted ) did not change the error.
Deleting the config.json produces a different error when launching.

**Log File**
[client.log](https://github.com/tModLoader/tModLoader/files/12566422/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/12566429/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/12566430/Natives.log)

**Steps to reproduce**
Launch tModLoader

**Expected Behavior**
the game should open normally

**Actual Behavior**
The console window opens and runs for a bit, then returns an error, and opens this web page https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#configjson-corrupted

**Reproduction frequency**
100% of the time

**Additional Information**
I have tried reinstalling both Terraria and tModLoader, as well as deleting the Terraria folder found in Documents/My Games
