### ISSUE TITLE
Main engine crash

### ISSUE THREAD

**Issue by Joemamaisfat767** [bluemagic123/tModLoader#3781]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

when launching game it keep crashing

### Log File

![371783787_844936380083043_8194683782692590189_n](https://github.com/tModLoader/tModLoader/assets/140173021/d925b517-0921-4179-8cdf-3ec6f4119bb4)

### Steps to reproduce

[First step]
Launch game

### Expected Behavior

the game lauches

### Actual Behavior

main engine crash

### Reproduction frequency

always

**Comment by Joemamaisfat767** [comment]
i used the wrong photo but its the same issue

**Comment by ghost** [comment]
you have to put the tML folder into GOG/Terraria/**game**
so its all in: "GOG/Terraria/game/tModLoader/"

**Comment by Joemamaisfat767** [comment]
> you have to put the tML folder into GOG/Terraria/**game** so its all in: "GOG/Terraria/game/tModLoader/"
it is in there though
![371501596_289201827063443_7816535321970867119_n](https://github.com/tModLoader/tModLoader/assets/140173021/ce719f6f-1ebf-4d9c-ba7f-96280eabff2c)

it is in there though
![371543350_213346125046504_2428186997631789445_n](https://github.com/tModLoader/tModLoader/assets/140173021/4a9577f0-e66a-4876-86b1-92b3fe3c4bcc)

**Comment by ghost** [comment]
Your Terraria is setup kinda weird, there should be a folder called "game" where all terraria files (.exe) are in. Try redownloading/reparing it, to see if it fixes it, that could be the problem.

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
