### ISSUE TITLE
Setting GlobalItem's CanRightClick to false for crates does not work

### ISSUE THREAD

**Issue by MarfMaster** [bluemagic123/tModLoader#3790]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I tried this in a globalitem CanRightClick function:
if (item.type == ItemID.OasisCrate)
{
return false;
}
return base.CanRightClick(item);
When trying to open the crate in-game, it didn't even hit the breakpoint I set at the if statement after I right-clicked it in my inventory and the crate opened as normal.
I tried rebuilding several times, nothing happened. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12527328/client.log)

### Steps to reproduce

1. Put this code into a globalitem class:
if (item.type == ItemID.OasisCrate) //all crates seem to ignore this
{
return false;
}
return base.CanRightClick(item);
2. Build the test mod
2. Try opening whichever crate you tried to block from being opened in-game, in this case the Ocean Crate

### Expected Behavior

Nothing should happen when trying to right-click the Oasis Crate, or it should follow the same rules as any non-crate item, meaning you'd be able to seperate multiple stacked items into smaller stacks by right-clicking them.

### Actual Behavior

The Oasis Crate gets opened.

### Reproduction frequency

100%

**Comment by Chicken-Bones** [comment]
`return false` is the default behaviour of the `GlobalItem` hook, so it makes sense that it does not prevent vanilla items from being openable. You could remove the `OasisCrate` from `ItemID.Sets.OpenableBag` and then use your `GlobalItem` to `return true` when you want it to be openable.

Otherwise, #3802 provides a 'bag specific' solution which would be able to interact nicely with modded bags/crates/etc.
