### ISSUE TITLE
Possible bug? More Info button opens in web browser when on Download Mods page

### ISSUE THREAD

**Issue by XepherTim** [bluemagic123/tModLoader#3798]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Clicking the More Info (?) button while on the Download Mods page opens the mod's steam workshop page in web browser. Does not happen on the Manage Mods page.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12571033/client.log)

### Steps to reproduce

1. Open Workshop from main menu
2. Open Download Mods page
3. Click More Info button on any mod

### Expected Behavior

Open in-game Mod Info page

### Actual Behavior

Mod's Steam Workshop page opens in web browser

### Additional Information

Assuming it isn't a bug, would be nice if it at least opened in the Steam Overlay web browser, especially for people playing in fullscreen mode.

**Comment by Solxanich** [comment]
Hello,

Yes, this is intentional behavior going forward. 
We were having various issues with the ingame description in previous versions not working, and this was the recommendation that followed. 

With respect to opening it in the Steam Overlay, we ultimately decided against it for three reasons:
1) the overlay browser is significantly weaker in general for security
2) It only scales ok on monitors at full HD resolution and 15" or greater.  This writes off a lot of laptops that are in our player base. 
3) Feature-wise, the overlay isn't consistent across Linux, Mac and isn't available to our GoG user base. So its currently difficult to maintain. There is also rumors of memory issues coming from it.

In the future (2024), when the new Steam UI stabilizes, we may re-evaluate using the overlay, but this is where we are today.

**Comment by XepherTim** [comment]
Thanks for the response, I thought reason 3 was likely but wanted to report just in case.

**Comment by PasiveClientSE5** [comment]
i would really like a toggle, as it opening a browser every time i want to view the more info gets really annoying, especially when comparing several similar mods(what just lead me to this post)

**Comment by IdrisQe** [comment]
Having not played Terraria in quite a while, coming back to see this was unpleasant, as someone who already dislikes how much worse Steam Workshop integration has made the user experience.

This is an old topic now but I'm also requesting a toggle. I don't care if it breaks sometimes, I don't want my browser constantly opening. If I wanted to look at things on Steam I would just browse the workshop directly, the ingame browser should have the option to keep as much of it _ingame_ as possible. Given the "Manage Mods" page still has these descriptions, there's no reason it can't be done.

My partner who is a lot more neutral about the workshop had a similar reaction of irritation when her browser kept opening, so it's not just my distaste for the workshop clouding my judgement here.

(Personally I was hoping another platform would have been found for hosting mods by now, since Workshop integration was originally supposed to be an alternative to the current browser, the team has suggested in the past that Steam Workshop wasn't widely liked when it was integrated, and that other options were being considered for the future... that along with Workshop causing problems for GOG, and being prone to mod install/uninstall bugginess, etc... but I guess that isn't going to happen at this rate since Steam is too popular, blehhhh...)
