### ISSUE TITLE
The skipMapSave argument is not used anywhere in the Player.SavePlayer function

### ISSUE THREAD

**Issue by il-gareni4** [bluemagic123/tModLoader#3823]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

The `skipMapSave` argument of the `Player.SavePlayer` function should, in theory, skip saving the map (line `InternalSaveMap(playerFile.IsCloudSave)`). That is, skipping saving the map does not work

### Expected Behavior

Skip saving map when argument `skipMapSave = true`

### Actual Behavior

The map is saved even when the argument `skipMapSave = true`

**Comment by JavidPack** [comment]
Since the parameter is unused, we have to assume it's either part of some feature removed from Terraria or a parameter used internally by the Terraria developers that we can't see in our code. 

The method is public, so I don't think we should consider removing the parameters since that could break mods. I also don't think there is any reason to implement it in tModLoader itself since it has no purpose. Mods could write their own SavePlayer method if they need something like that for some reason, but I can't think of any reason a mod would be saving players, that seems very sketchy as well.

Therefore, I'll be closing this, we won't be doing anything with this.
