### ISSUE TITLE
Gave me an error.

### ISSUE THREAD

**Issue by MeleeGamer** [bluemagic123/tModLoader#3831]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Installer gave me an error message when I tried to install tModloader

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12705230/client.log)

### Steps to reproduce

1. Open start-tModLoader-FamilyShare.bat
2. For me, that was all.

### Expected Behavior

I'm pretty sure it should just add tModLoader to my steam library, right?

### Actual Behavior

![image](https://github.com/tModLoader/tModLoader/assets/112276077/1013d62e-389f-40de-aead-94b2fbbc1c6b)
Showed this error message.

### Reproduction frequency

Every time.

### Additional Information

I'm accessing Terraria through Steam shared libraries,
Yes, I currently have access to the game.

**Comment by Antirhinnum** [comment]
`start-tModLoader-FamilyShare.bat` does not install tModLoader, it tries to start it from whatever folder you're in.
Did you properly follow the [manual installation steps](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation)?

**Comment by JavidPack** [comment]
As the error message says, you installed in the wrong location. Follow the steps linked above. Come to Discord if you need more help.

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
