### ISSUE TITLE
Method skipping in stacktraces

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3845]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I managed to find a reproducible case where a stacktrace lacks critical information about which mod caused the error, see below. There _should_ be another entry in the stack between Insert and ModifyInterfaceLayers belonging to a mod.

```
[12:12:39.950] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Terraria.ModLoader.SystemLoader.ModifyInterfaceLayers(List`1 layers) in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 363
   at Terraria.Main.DrawInterface(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 37959
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 53499
   at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52777
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52764
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 264
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 238
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 213
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 78
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in tModLoader\Terraria\MonoLaunch.cs:line 64
   at System.Threading.Thread.StartCallback()
```

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12737471/client.log)

### Steps to reproduce

1. Download the two mods: [mods.zip](https://github.com/tModLoader/tModLoader/files/12737476/mods.zip)
2. Install the stable version for september: <https://github.com/tModLoader/tModLoader/releases/tag/v2023.06.25.36>
3. Place mods into tmodloader/Mods, enable them ingame
4. Aquire any weapon from the Clicker Class mod, and hold it, the UI should disappear

### Expected Behavior

Stack trace shows the mod "ZoneTitles" in the stacktrace

### Actual Behavior

no mod in the stacktrace

### Reproduction frequency

100%

### Additional Information

This error happens due to removing an interface layer another mod relies upon when calling Insert, presumably using -1 as the index because of it.

It is fixed in "Clicker Class" in october that's why I provided the mod files <https://github.com/SamsonAllen13/ClickerClass/commit/90577499a9beb026bf4c2d5b8b7fa10272a5dbbc#diff-7923d780a531aa0bf98cc04613c1e21aa01116fe71d49449613ceae088f39cb7R41>

**Comment by Chicken-Bones** [comment]
This happens because of a JIT optimization employed by .NET and cannot be avoided when your assembly (ClickerClass) is compiled with optimizations enabled.

When reading a release mode stack trace, there's one special fact you must know. Stack traces do not show where a call came from, they show where a call _will go_. That is, they contain return addresses, not call addresses. The reason the stack trace shows `List.Insert` is because the last line of code in  `ZoneTitles.UISystem.ModifyInterfaceLayers` is `List.Insert`. There's no reason to return to `ZoneTitles.Common.Systems.UISystem.ModifyInterfaceLayers` after inserting, so the stack is cleaned up before the `List.Insert` call, and the return address stays as `SystemLoader.ModifyInterfaceLayers`.
https://github.com/TwilightMage/ZoneTitles/blob/1.4.3/Common/Systems/UISystem.cs#L71

As always, here's an excellent blog by Raymond Chen <https://devblogs.microsoft.com/oldnewthing/20170505-00/?p=96116>

You can see the optimization at play for yourself if you run the version of `ClickerClass` you linked in release, and breakpoint at `ModifyInterfaceLayers`, step through to the `List.RemoveAt` call, then switch to disassembly view.

You should see x86 like this.
```
00007FFB39CE96DC  mov         rcx,rsi  
00007FFB39CE96DF  mov         edx,edi  
00007FFB39CE96E1  add         rsp,28h  
00007FFB39CE96E5  pop         rsi  
00007FFB39CE96E6  pop         rdi  
00007FFB39CE96E7  jmp         System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib]].RemoveAt(Int32) (07FFB96145320h)  
```

Note `jmp` instead of `call`. As soon as you step into that `jmp` you will see the stack trace window change from
![image](https://github.com/tModLoader/tModLoader/assets/388233/6e16b377-a154-4921-bc79-4612345216ab)
to
![image](https://github.com/tModLoader/tModLoader/assets/388233/6bbdf1b3-1ee7-4f56-923a-0bd3774f9061)

**Comment by direwolf420** [comment]
So the solultion is to publish ClickerClass as a debug build to get more informative strack traces? Or ZoneTitles? Or both?
My goal is to have "useful" stack traces that make it easier to see which mod causes what error, without the user having to do process of elimination with the mod list to find the culprit.

**Comment by Chicken-Bones** [comment]
In this case, the crash occured in ZoneTiles so it's completely beyond your control. This is the reason why unoptimized assemblies are used for debugging and diagnosis, but the performance costs are too high in some cases to have debug mode publishing as a default

**Comment by Chicken-Bones** [comment]
Note that the case where a culprit mod is absent from a stack trace is relatively rare, though not impossible. A developer looking at the code can normally tell when a stack trace isn't telling the full story.

If this was a particularly common case it would be more reasonable to insert `try/catch` statements in tML hooks

**Comment by direwolf420** [comment]
or rework interface layers to support topoligical sorting
