### ISSUE TITLE
Assistant needed

### ISSUE THREAD

**Issue by FengYing013** [bluemagic123/tModLoader#3849]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Hi, I believe the log shows the report of a corrupted file named config, my friend replace the file with a working config, and then another issue was reported.

![98b2e1dffbfdd6f7ac8297e5e9feac49](https://github.com/tModLoader/tModLoader/assets/146407517/16934300-668a-4ac2-aa7b-2a6f69bd6481)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12755868/client.log)

**Comment by JavidPack** [comment]
Can you try to load normal tModLoader instead of preview? If that doesn't work, you should be able to make the `D:\UserData\My Documents\My Games\Terraria\tModLoader-1.4.3` folder yourself and avoid this issue.

If you have any other issues, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). We don't do support here on GitHub.
