### ISSUE TITLE
Add skin to npc

### ISSUE THREAD

**Issue by lampcccc** [bluemagic123/tModLoader#3850]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Why do every NPC look so single?
**Why can't NPCs have multiple looks and postures?**Just like the skin in LOL

### What does this proposal attempt to solve or improve?

No response

### Which (other) solutions should be considered?

No response

**Comment by JavidPack** [comment]
Town NPC do have one, for party hats. Pretty sure those are hard-coded to town npc though.

For normal NPC, typically mods would draw a specific frame of animation specific to a skin (like how regular mimics work), manually draw a different texture, or just use inheritance to make different versions of the same ModNPC class.

I think there are sufficient ways that a modder could implement this for their own NPC. I don't think tModLoader itself has any reason to implement something like this, since it is a big deviation from Terraria, but a mod could certainly add this functionality to all NPC with clever coding.

If you need help implementing this in your own mod, the [Discord chat](https://tmodloader.net/discord) is a great place to ask.
