### ISSUE TITLE
Change the Zenith to the original version

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#3861]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

In the original version, the more the Zenith appears as the attack speed increases, the more accurate it is.Can the effect of zenith affected by attack speed in the original version be done separately in tModLoader?

**Comment by JavidPack** [comment]
Test char with melee speed accessories:
[[c-00ff00-MyMan].zip](https://github.com/tModLoader/tModLoader/files/12796439/c-00ff00-MyMan.zip)

Interesting. It seems like the 1st throw is always more accurate to the cursor, and other swords have more randomness and might home in on other enemies.

In tModLoader, it always throws 3 swords, but in Terraria having high melee speed makes it throw 2 swords (less, not more as suggested by issue author. See notes in https://terraria.wiki.gg/wiki/Zenith) , but I think the use time is faster, if I'm correct in my observation. Theoretically it's throwing the same number of swords per second, but just at different patterns.

Since throwing 2 swords more frequently is effectively different than throwing 3 swords less frequently due to the homing/randomization of non-1st projectiles, I can see that this would be something users would notice. Single target DPS might suffer.

I'm not sure how to restore the original behavior, I tried changing Zenith to DamageClass.Melee instead of MeleeNoSpeed and that just caused more swords per use. I'm sure @Chicken-Bones might have an idea, or might deem it a necessary concession for all the other benefits our changes have brought.

**Comment by JavidPack** [comment]
Looking into this, we've discovered that the issue is a bit hard to fix. We have an idea, `It's technically possible to restore the vanilla behavior, just set attackSpeedOnlyAffectsAnimation and add useLimitPerAnimation of 3, possibly with something that resets itemTime to 0 on animation start (maybe shootsEveryUse will do it)`, but it likely won't restore the full Terraria behavior.

Thanks for the report. For now, we'll keep this issue open so others can upvote if they truly want this fixed, but we won't work on this at this moment. It was also brought up in our discussions that the Terraria behavior with high melee speed is actually worse for the player because it is less likely to protect the player by damaging nearby enemies. The theoretical DPS should be the same either way.

**Comment by SSS100015aqlp** [comment]
However, the zenith has penetration, when attacking behind the enemy, the non-tracking part can deal two damage, while the tracking part only deals one damage, there is still a big difference in damage per second.

**Comment by SSS100015aqlp** [comment]
@JavidPack However, the zenith has penetration, when attacking behind the enemy, the non-tracking part can deal two damage, while the tracking part only deals one damage, there is still a big difference in damage per second.

**Comment by SSS100015aqlp** [comment]
@Chicken-Bones Hello, can you help me to deal with my request? The flexibility of the Zenith Sword in TML is too poor. In the case of high firing rate, the Zenith Sword reacts quickly and can catch up with the BOSS with high moving speed. In this way, the damage it can deal will be higher. We should pursue a shorter kill time. It is enough to deal with other things, but I I want it to react faster at high attack speed like the original.
I sincerely request your help to revise it, if you are willing to do, I will be very grateful.
