### ISSUE TITLE
Problem with multiplayer(all version)

### ISSUE THREAD

**Issue by Woran991** [bluemagic123/tModLoader#3915]
### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

GOG

### This bug affects

Gameplay as a Player

### Description

None of the versions of Tmodloader support network play through LogMein Hamachi, even without the use of mods
Terraria and tmodloader from steam are not available in my region
3 months ago everything worked

### Log File

[Natives.log](https://github.com/tModLoader/tModLoader/files/13256257/Natives.log)
[client.log](https://github.com/tModLoader/tModLoader/files/13256258/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/13256259/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13256260/Launch.log)

### Steps to reproduce

1. Launching tmodloader
2. Launching Hamachi and adding to the network with the host
3. Copying host IP address to multiplayer address
4. Endless connection

### Expected Behavior

Connecting to the server

### Actual Behavior

Endless connection

### Reproduction frequency

100%

### Additional Information

Regular terraria works, which means the problem is not Hamachi
None of us can connect to each other via tmodloader
Other similarities of hamachi have been disabled
The version we successfully played on 3 months ago produces the same eternal loading
We are all on the same version of tmodloader

**Comment by JavidPack** [comment]
I'm not seeing anything specific here, seems like just normal networking issues. I would suggest just not using Hamachi, just connect normally with ip address. If you need more help, come to Discord support.

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). Be sure to post your logs when asking for support.
