### ISSUE TITLE
TmodLoader Error

### ISSUE THREAD

**Issue by erozs19** [bluemagic123/tModLoader#3924]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When i open the TML it crash.
I only download the tModLoader.zip.
I need the other 3 archives to run TML??

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). Be sure to post your logs when asking for support.
