### ISSUE TITLE
Game crushes, when i'm beating WoF

### ISSUE THREAD

**Issue by ArtUnd209** [bluemagic123/tModLoader#3963]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I played terraria with Calamity mod, Calamity Music mod, Project tRu and Boss Checklist. So when i killed WoF in Revengeance mod, game just crushed, please help. [client-crashlog.txt](https://github.com/tModLoader/tModLoader/files/13552247/client-crashlog.txt) 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/13552252/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/13552253/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/13552254/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13552255/Natives.log)

### Steps to reproduce

Create the Large world on expert
Enable Revengeance mod
Kill WoF
And game crushes

### Expected Behavior

My world should become hardmode

### Actual Behavior

Game jist crushes

### Reproduction frequency

2 times that the amount of time I killed WoF

**Comment by JavidPack** [comment]
I'm not seeing a cause in the logs you posted, but those mods have had updates since this error report, so I would try again and see if it's working now. 

If you still have issues, you'll need to disable mods to determine which single mod is causing the issue and seek support from that mod's author.
