### ISSUE TITLE
"looseDllReference" build property

### ISSUE THREAD

**Issue by Tyndareus** [bluemagic123/tModLoader#3975]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

I would like there to be a second dllReference property in the build.txt that allows for loose dlls to be loaded, right now its force loaded and assumed that the dll would be C#.
However, I would like to load a C++ dll and obviously C++ isn't IL, being able to have the file exist with the mod would allow me to utilize imports for better code.

I set no to personally contributing because its just going to be a property and then including the file in the tmod packing. The rest is on the developer of the dll to run.

### What does this proposal attempt to solve or improve?

For myself I can utilize faster and more efficient code to manage things like a virtual file system or add necessary layers of security to this unprotected modding system.

For other experienced developers they may also be able to utilize the C++ side of things to process more actions and calculations without potentially losing performance because their boss spawns a load of calculated dust or needs to calculate radial projections with some bullet hell.

Granted, I may be the only one that uses this. But there are benefits to all if they wished to learn even basic C++.

**Comment by Chicken-Bones** [comment]
You can package a `.dll` in your mod without including it in the `dllReferences` list. tML cannot load native dlls for you, but you can load your own by using `GetStream` or `GetBytes` on `mod.File` to obtain the packed dll file data during mod loading. Most systems require writing the native dll to disk before it can be loaded so you'll also have to do this.

We do not recommend using native dlls because:
- It is challenging to build all the required versions for all platforms and architectures.
- It is more difficult to verify whether a mod contains malware.

**Comment by steviegt6** [comment]
Unless you're dealing with variadic arguments, you can typically pretty easily interface with existing system APIs and write relatively performant code in .NET. You'll usually be able to do a good job of avoiding native dependencies altogether.
