### ISSUE TITLE
me and my friend can't join eachother's worlds

### ISSUE THREAD

**Issue by deadvoltage** [bluemagic123/tModLoader#3976]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

whenever we try to join eachother we never are able to connect to eachothers world and it seems to only be happening with the new update

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://discord.gg/tmodloader). Be sure to post your logs when asking for support.
