### ISSUE TITLE
I cant find the Windows download link

### ISSUE THREAD

**Issue by zyroPyr** [bluemagic123/tModLoader#4001]
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

been searching for a while and i cant find the link for the windows download

**Comment by fishiatee** [comment]
What do you mean by Windows downloads?

If you meant tModLoader for Windows, you can install it on Steam as it's a free DLC for Terraria; if you own Terraria on GOG instead, since 1.4 tModLoader does not have separate Windows/Linux builds anymore. You can see how to install it [here.](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players)

**Comment by JavidPack** [comment]
Yes, manual install downloads are listed in <https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation>
