### ISSUE TITLE
PostSellItem's item parameter gives the wrong item if the NPC's shop is full

### ISSUE THREAD

**Issue by MingCate** [bluemagic123/tModLoader#4069]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

When an NPC's shop is full, items sold to them will not be passed to the item parameter of PostSellItem. Instead, the item at index 0 of the shop is passed.

### Additional Information

Items sold in a full shop disappear for good (this is intended vanilla behavior), however this leads to confusing results with PostSellItem. The item passed to PostSellItem's as a parameter will instead be the item at index 0 of the shop, which results in weird behavior for any modders using the item parameter. I suggest that a clone of the sold item be passed to PostSellItem instead, and maybe also add a bool parameter indicating if the NPC's shop was full or not.

**Comment by JavidPack** [comment]
Seems that some tModLoader changes have been lost accidentally in moving to 1.4. In tModLoader, when selling to a full shop inventory, the sold item should replace the 2nd to last slot instead of disappearing. I've restored this lost change, so the item passed in is now correct.

I also fixed a similar issue with selling items back to the shop that they sell themselves.
