### ISSUE TITLE
Language Pack with malformed json prevents game from launching

### ISSUE THREAD

**Issue by fuzzymelon12** [bluemagic123/tModLoader#4084]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

main engine crash something about pumpkin pie
![Screenshot (28)](https://github.com/tModLoader/tModLoader/assets/161412240/1df934c1-dfad-4f77-a270-49feca5b885e)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14414390/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/14414391/environment.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/14414392/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14414393/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14414394/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/14414395/terrariasteamclient.log)

### Steps to reproduce

1. have a normal account
2. open the app
3. wait

### Expected Behavior

[client.log](https://github.com/tModLoader/tModLoader/files/14414368/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/14414369/environment.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/14414370/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14414371/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14414372/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/14414373/terrariasteamclient.log)

### Actual Behavior

cant play the game

### Reproduction frequency

happened yesterday, was able to fix it briefly then happened again today

### Additional Information

I have 1 character and 1 world. multiple mods like calamity, alchemist NPC lite, and luiafk. no more than 1 massive content mod

**Comment by JavidPack** [comment]
Looks like an error with one of your resource packs. In the error, it mentions `ItemTooltip.PumpkinPie`, so the culprit is likely whichever resource pack is editing that item name.  (Not a Mod)

You can follow these instructions to disable all resouce packs: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#disable-all-resource-packs

After that, go in game and enable them one at a time to figure out which one is causing the error. 

Another option is visit the workshop pages for all your subscribed resource packs and see which one updated most recently. That is the most likely culprit

Let me know which resource pack was the issue so that I can fix this in tModLoader so that broken packs won't cause a crash.

**Comment by fuzzymelon12** [comment]
it worked. thank you. I know nothing about computers and code and stuff

**Comment by JavidPack** [comment]
Thanks for the report. I've added some safeguards to future versions of tModLoader. Your error seem to have originated from the Butterscotch Cinnamon Pie pack.
