### ISSUE TITLE
tModloader does not detect .Net SDK 6 on NixOS

### ISSUE THREAD

**Issue by TailstheFox92** [bluemagic123/tModLoader#4102]
### Version

Latest 1.4.4-preview

### OS

Linux

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Tmodloader does not detect .Net SDK 6 even when installed, distro is NixOS Unstable

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14551581/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/14551582/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14551583/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14551584/Natives.log)

### Steps to reproduce

1. Install `dotnetCorePackages.sdk_6_0` package by declaring in configuration.nix
2. Launch tModloader
3. Click on Workshop > Develop Mods

### Expected Behavior

.Net SDK 6 should be detected by tModloader

### Actual Behavior

.Net SDK 6 is not detected and prompts user to install

### Reproduction frequency

Consistent

### Additional Information

This is the result when running `dotnet --list-sdks`
![image](https://github.com/tModLoader/tModLoader/assets/41931137/ad63eb7b-3e32-4904-8849-7c83f53414ea)

**Comment by JavidPack** [comment]
According to your `environment-client.log`, the dotnet sdk isn't in `PATH`. My guess is you ran `dotnet --list-sdks` after installing, which is why it ran correctly in your terminal session. The linux dotnet sdk install script will update PATH for the terminal session, but it won't be permanent. (I don't know how the NixOS dotnet sdk install works, but I assume it runs the install script since it's not one of the supported package managers.)

You have a couple options:

One is follow the instructions on https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#set-environment-variables-system-wide to add it to the path so that when tModLoader is launched it has access to the dotnet command. This will likely be useful for Visual Studio Code also having access to the dotnet sdk install.

Another option is to set an environment variable so that tModLoader knows where dotnet is installed. You can do that by: Visit the Steam properties for tModLoader. To do this, right click on tModLoader in Steam, select "Properties", and then find the "Launch Options" box in the "General" tab. Type in the following for the launch options and close the window: `DOTNET_ROOT=/home/deck/.dotnet %command%` (replace the path with your path to the folder containing the dotnet executable)

![284679681-ee0fe72e-dc38-4593-9bcc-95c10b0998d2](https://github.com/tModLoader/tModLoader/assets/4522492/fefbedaf-59df-47ff-8b3b-cd58aefd4829)


Feel free to come by our [Discord chat](https://discord.gg/tmodloader) if you run into any issues and need to chat.

**Comment by TheSkyFather** [comment]
Hi my dear friend. I recorded a video about this problem. Solved

https://youtu.be/SagJ4sI45lk
