### ISSUE TITLE
Localization key for Info Displays doesn't work.

### ISSUE THREAD

**Issue by Cedcoder66** [bluemagic123/tModLoader#4123]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

I am currently working on a mod for displaying character stats using Info Displays and wanted to add translations, but the localization key for info displays (`Mods.{modName}.InfoDisplays.{contentName}.DisplayName`) doesn't seems to work. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14652658/client.log)

I doubt this will provide any help but here it is anyway.

### Steps to reproduce

1. Create a custom info display script.
2. Add a localization key both english and/or non-english
3. Open any world, hover your mouse over the info display.

### Expected Behavior

The localization files for info displays should use the display name, if it has any. (In my case it does)

![image](https://github.com/tModLoader/tModLoader/assets/143538073/8f3e97dd-fe08-4399-a445-331eecab84d0)

Same for non-English localization files, in this case French for example.

![image](https://github.com/tModLoader/tModLoader/assets/143538073/b6f4953d-8ea9-498a-a8f1-3f245a372bbf)

### Actual Behavior

The English localization file uses the **content name** instead of the display name.

Using the "a1_Damage" content name for instance:

![image](https://github.com/tModLoader/tModLoader/assets/143538073/86c638cf-9324-4485-91cd-53b33ec6a751)

And when using the French localization files, it uses the **full key path** instead:

![image](https://github.com/tModLoader/tModLoader/assets/143538073/76fae431-ad51-4c42-ad1e-da95902d9be5)

### Reproduction frequency

100%

### Additional Information

- Using `` Language.GetTextValue("Mods.CharacterStats.a1_Damage.DisplayName"); `` does the same issue.
- Removing the underscore in "a1_Damage" did not do anything either.

**Comment by JavidPack** [comment]
It's working on my end. I can't really tell where the issue is on your side since you didn't link to the source code. If you want to post a zip or github link to your mod's source code either here or on the Discord chat I can tell you what is wrong, but my guess is you are editing the wrong .hjson file, or you have duplicate hjson files, or the hjson is using a prefix, or something like that.

I did, however, find an issue that the hjson files aren't being auto-populated with keys for InfoDisplays. I'll be able to fix that for a future release. You shouldn't need to manually add localization keys, that's a bug.

As a sanity check, are you sure the keybinds entries in these files are the ones being used?

**Comment by Cedcoder66** [comment]
Hello, I know this issue is closed but just in case, here's the github for the mod with it's source code.
https://github.com/AE-Studios-Development/Terraria-Display-Character-Stats

> As a sanity check, are you sure the keybinds entries in these files are the ones being used?

The localization for keybinds does work, however there are 2 seperate keys for it and the one outside the mod key is added automatically. I assume that's normal thought.

![image](https://github.com/tModLoader/tModLoader/assets/143538073/fcd6b028-e2d0-4986-b0cd-1def4d82ba40)

**Comment by JavidPack** [comment]
No, that is not normal. So your issue is your localization file is named `en-US_Mods.CharacterStats.hjson`, but you have `Mods` and `CharacterStats` sections within the file. The `Mods.CharacterStats` part of the filename is a common prefix for all of the keys within the file. (https://github.com/tModLoader/tModLoader/wiki/Localization#prefix). As a result, the `a1_Damage.DisplayName` entry you added has a key of `Mods.CharacterStats.Mods.CharacterStats.InfoDisplays.a1_Damage.DisplayName`, which is why they aren't being used.

To fix this, simply delete the `Mods` and `CharacterStats` nesting and move everything over. Your final `en-US_Mods.CharacterStats.hjson` file will look like this:

```
Keybinds: {
	StatVisibilityKeybind.DisplayName: Toggle Stats Visibility
	ChangeStatClassKeybind.DisplayName: Change Damage Class
}

InfoDisplays: {
	d1_Aggro.DisplayName: Enemy Aggro
	a5_ArmorPenetration.DisplayName: Armor Penetration
	a3_AttackSpeed.DisplayName: Attack Speed
	a2_CriticalChance.DisplayName: Critical Chance
	a1_Damage.DisplayName: Damage
	b2_Endurance.DisplayName: Endurance
	c2_JumpHeight.DisplayName: Jump Height
	a4_Knockback.DisplayName: Knockback
	b3_LifeRegeneration.DisplayName: Life Regeneration
	d2_Luck.DisplayName: Luck
	e2_ManaCost.DisplayName: Mana Efficiency
	e1_ManaRegeneration.DisplayName: Mana Regeneration
	e3_MaxMinions.DisplayName: Max Minions
	c3_MiningSpeed.DisplayName: Mining Speed
	c1_MovementSpeed.DisplayName: Movement Speed
	e4_MaxSentries.DisplayName: Max Sentries
	b1_Defense.DisplayName: Defense
	d3_FishingPower.DisplayName: Fishing Power
}
```

Build and reload your mod and the other language files will update, then you can fix them too. Or you can fix them manually at the same time.

**Comment by Cedcoder66** [comment]
Alright, thank you very much!

**Comment by Cedcoder66** [comment]
Yep, that fixed it, thanks again.
