### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by Alfredoes234** [bluemagic123/tModLoader#4127]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Cant open the game once fullscreen or a certain resolution is set on config and then it produces a memory error, whereas it will work normally in normal terraria.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14671047/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14671048/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14671049/Natives.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/14671051/environment-client.log)

### Steps to reproduce

1. Try to open game

### Expected Behavior

Open when fullscreen or set at 1920 x 1080, instead of crashing

### Actual Behavior

Should allow me to use 1920 x 1080 but in game when you do not set it in config it does not work

### Reproduction frequency

Happend for today and yesterday

**Comment by sebastienvercammen** [comment]
I have exactly the same problem, except fullscreen is not the only trigger for this error. On Win11, Steam, 1.4.4-stable.

Terraria without TML works perfectly.

**Comment by JavidPack** [comment]
Hm, from our [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#check-nativeslog), the suggestions for this issue seem to be: 

If it says "System.AccessViolationException: Attempted to read or write protected memory.", follow the [Fresh Install](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#fresh-install) and [Fresh Install Terraria](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#fresh-install-terraria) steps.

Give that a try.

**Comment by Chicken-Bones** [comment]
Is there any resolution you can open the game on?

**Comment by sebastienvercammen** [comment]
@JavidPack I've tried fresh installs multiple times, of both Terraria and TML, they never work via Steam.

When I compile TML myself via the stable branch, it mostly works normally until I try to enable CalamityMod. Enabling Calamity means it'll flip a coin. If it decides to want to work, it'll work once (and I can play for hours w/o issue as long as I don't restart the game and don't reload mods), then it stops working for a day or so, before eventually some random circumstances magically make it work again. Sometimes recompilation / clean git clone / ... are necessary before it ever works again. Other mods, like Recipe Browser and Cheat Sheet, always work perfectly w/o a hitch.

I've rebuilt TML a couple hundred times, sometimes the new build works sometimes it doesn't. Sometimes restarting the same build works once it crashed, but 9/10 it doesn't. Including from clean git clones each time. I've posted more details on the Discord support chat.

Always boils down to System.AccessViolationException.

Tried with antivirus disabled (using only Windows Defender), used DISM /RestoreHealth and sfc /scannow to check Windows health, memtest comes back perfectly clean, and Windows' Driver Verifier is perfectly clean as well. This is a fairly new desktop.

Also tried both w/ the local dotnet it downloads by default as well as my system dotnet (always 6.x), same issue. Reinstalled system .NET multiple times, and deleted the full tModLoader multiple times as well (both on the Steam install and on the custom built).

Tried rebooting between each attempt as well, no luck.

I'm quite invested in this and willing to hop on Discord to stream my screen if that can help, or otherwise provide any info. As it is, TML is unplayable for me.

Latest logs, of my latest run/build that boots but crashes on Calamity load, are attached.
[Launch.log](https://github.com/tModLoader/tModLoader/files/14707321/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14707322/Natives.log)
[client.log](https://github.com/tModLoader/tModLoader/files/14707323/client.log)

This crash also shows up in Event Viewer:
```
Application: dotnet.exe
CoreCLR Version: 6.0.1423.7309
.NET Version: 6.0.14
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF9067B21D1 (00007FF9065E0000) with exit code c0000005.
```
```
Faulting application name: dotnet.exe, version: 6.0.1423.7309, time stamp: 0x63cf74d7
Faulting module name: coreclr.dll, version: 6.0.1423.7309, time stamp: 0x63cf6c9b
Exception code: 0xc0000005
Fault offset: 0x00000000001d21d1
Faulting process id: 0x0x404C
Faulting application start time: 0x0x1DA7BD490824D19
Faulting application path: D:\repos\tModLoader\src\tModLoader\Terraria\bin\Debug\net6.0\dotnet\6.0.14\dotnet.exe
Faulting module path: D:\repos\tModLoader\src\tModLoader\Terraria\bin\Debug\net6.0\dotnet\6.0.14\shared\Microsoft.NETCore.App\6.0.14\coreclr.dll
Report Id: f96e71d7-09ee-4ebe-acca-f5476da1dd93
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Chicken-Bones** [comment]
@sebastienvercammen your issue is different to the OP as it happens in `MonoMod`, not when setting display resolution. Please make a separate issue. Coming to the Discord is recommended. Can you reproduce after disabling Calamity?

**Comment by sebastienvercammen** [comment]
@Chicken-Bones Yes, it reproduces without Calamity when using the Steam release. Attached, you'll find the logs for the Steam release that crashes before any mods load.
[Launch.log](https://github.com/tModLoader/tModLoader/files/14711148/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14711150/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/14711152/terrariasteamclient.log)
[client.log](https://github.com/tModLoader/tModLoader/files/14711154/client.log)

**Comment by Alfredoes234** [comment]
> Hm, from our [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#check-nativeslog), the suggestions for this issue seem to be:
> 
> If it says "System.AccessViolationException: Attempted to read or write protected memory.", follow the [Fresh Install](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#fresh-install) and [Fresh Install Terraria](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#fresh-install-terraria) steps.
> 
> Give that a try.

Tried that but did not solve anything

**Comment by Alfredoes234** [comment]
> Is there any resolution you can open the game on?

It can up to something like 1920 x 1030 without pre setting it or something similar but if I try to fullscreen it crahses. But really I want 1920x1080.

**Comment by Chicken-Bones** [comment]
@Alfredoes234 please come to the Discord and make a support thread. Ping me and I'll work on resolving your issue

**Comment by Alfredoes234** [comment]
> @Alfredoes234 please come to the Discord and make a support thread. Ping me and I'll work on resolving your issue

I posted it in the discord support and someone helped me turns out it just needed to be set as opengl on the command line for steam
