### ISSUE TITLE
Daybreak's & Solar Eruption's Explosions Can Critically Strike

### ISSUE THREAD

**Issue by lace-wing** [bluemagic123/tModLoader#4161]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Daybreak's and Solar Eruption's explosions(`ProjectileID.DaybreakExplosion` and `ProjectileID.SolarWhipSwordExplosion`) can and will crit, which they don't in vanilla Terraria.

### Additional Information

I didn't see a better fix than manually disabling crit in `ModifyHit` or setting the projs' `CritChance`; but maybe I'm blinded.

**Comment by Chicken-Bones** [comment]
In vanilla, only `melee`, `magic` or `ranged` projectiles can crit. In tML, `Default` projectiles can also crit, but only if they are spawned by using an item with crit chance, or have some inherent `CritChance` from `SetDefaults`.

I wonder if there are any other non-default classed weapons which spawn default classed projectiles.

I think the tML behavior is acceptable, and these two weapons are an exception/oversight. I will ask the Terraria team if they should perhaps crit. Otherwise we can set `CritChance = 0` after spawning them.

**Comment by Chicken-Bones** [comment]
Confirmed, they intentionally can't crit. I suggest we just set `CritChance = 0` after the `NewProjectile` calls. The other option would be adding a new `bool InheritCritChance[]` set to `ProjectileID` but ehh
