### ISSUE TITLE
GlobalTile Drop Hook not working for tombstones (tile entity)

### ISSUE THREAD

**Issue by tris790** [bluemagic123/tModLoader#42]
Since Tombstone aren't killed the same way, we cannot return false to prevent them from dropping their item.

Code used:
public override bool Drop(int i, int j, int type)
        {
            if (type == TileID.Tombstones)
                return false;   //It will return false, but still drop the item
            else
                return true;
        }

**Comment by gorateron** [comment]
Are you trying to compare an item type to a tiletype?? I'm not really getting it here

**Comment by gorateron** [comment]
Actually this is a larger problem with the drop hook, considering it only works for 1x1 tiles and a tombstone is bigger. All other tiles drop their items in its CheckXxY method, so this requires more thought than I anticipated. I'll update the wiki for now so that it is clear the drop hook currently only works for 1x1 tiles.

**Comment by Jofairden** [comment]
Actual fix commit: ea3d3c44b56ce6662e85830e4553053ceb4f0c23
