### ISSUE TITLE
Inconsistent Results from Collision.CheckAABBvLineCollision in Certain Cases

### ISSUE THREAD

**Issue by hezuo1hao** [bluemagic123/tModLoader#4213]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

When the line is fully enclosed by the AABB, I noticed that the method returns false, which is not logically consistent.

### Steps to reproduce

1. Utilize CheckAABBvLineCollision and ensure the line is completely enclosed within the AABB.
2. Check the returned result.

### Expected Behavior

The method should return true.

### Actual Behavior

The method returns false.

### Reproduction frequency

100%

### Additional Information

I'm using the overload CheckAABBvLineCollision(Vector2 objectPosition, Vector2 objectDimensions, Vector2 lineStart, Vector2 lineEnd, float lineWidth, ref float collisionPoint).
I suspect that the other overload CheckAABBvLineCollision(Vector2 aabbPosition, Vector2 aabbDimensions, Vector2 lineStart, Vector2 lineEnd) might have a similar issue.

**Comment by JavidPack** [comment]
I talked to the Terraria devs, they won't fix this since the method is used in too many places to do proper quality assurance checks. We won't fix it as well for the same reasons and because mods are using the method as it currently is.

You'll need to write your own method or use additional checks if this specific case is important to your use case.

**Comment by hezuo1hao** [comment]
Okay, I'll figure it out on my own
