### ISSUE TITLE
inventory swap/duplication

### ISSUE THREAD

**Issue by Orca223** [bluemagic123/tModLoader#4216]
### Version

Latest 1.4.3-legacy

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Whilst fighting skeletron prime, both of my two friends' games froze, leaving me alone to fight the boss while they got focused (but took NO damage). After about 2-3 minutes of "semi-solo" gameplay, their games both crashed (one of them was the world host) resulting in both leaving the world. This left me alone in a world that wasn't mine. The weirdest part was that the second their games crashed, my game got sped up to about 5x of the regular speed, which included movement, gravity, hit speed, enemy hit speed and enemy movement, but not affecting the cooldown for potions. At the same time, my inventory, armor and accessories got swapped out for the world host's inventory. (I was playing summoner and he was playing mage -> both became identical mage builds). This glitch is still going and all my summoner items were still lost even after restarting the game.

### Steps to reproduce

1. we don't really know how this happened but before spawning skeltron prime we tried to spawn the destroyer, which spawned with 250 hp and died instantly without any drops.

**Comment by JavidPack** [comment]
That sounds like an extremely unique bug, something that definitely isn't something we can replicate, especially since you are on 1.4.3, which is old.  

Your best option is to restore your players from backups and then use any item spawner mod to give yourself any items that might have been lost since the last working backup player file. https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#world-and-player-backups
