### ISSUE TITLE
Shadowflame Apparition Sprite and its Glow Sprite have questions

### ISSUE THREAD

**Issue by hezuo1hao** [bluemagic123/tModLoader#4221]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Shadowflame Apparition Sprite and its Glow Sprite There is a texture misalignment issue
It should be due to the inconsistent texture width between the Shadowflame Appearance Sprite and its Glow Sprite

### Steps to reproduce

1.Open the game and find a Shadowflame Apparition through any method to see it issue

### Expected Behavior

https://terraria.wiki.gg/images/6/63/Shadowflame_Apparition.gif

### Actual Behavior

![3%7X~5{83@ 0%))9V~VSG`C](https://github.com/tModLoader/tModLoader/assets/110245158/decd1929-a858-46b7-9c01-51361a92582c)

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Turns out this is a Terraria bug from what I can tell. I've reported this to them, so we should see a fix in the next update.

In the meantime, download this resource pack I made with the fixed sprite and place it in `\Documents\My Games\Terraria\tModLoader\ResourcePacks` and then enable it in-game. 

[FixShadowflameApparition.zip](https://github.com/tModLoader/tModLoader/files/15383100/FixShadowflameApparition.zip)
