### ISSUE TITLE
"Version string was too short or too long" when clicking "Develop mod" button

### ISSUE THREAD

**Issue by Arsen1yGD** [bluemagic123/tModLoader#4253]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

So, when I click "Develop mod" in "Workshop" menu, game crashes because of System.ArgumentException: Version string was too short or too long. I used only Project tRu, but it's still crashing without it.

### Log File

[client.log](https://github.com/user-attachments/files/15585974/client.log)

### Steps to reproduce

1. Make sure you use 1.4.4 June stable update.
2. Run tModLoader.
3. Click "Workshop", and then "Develop mod".

### Expected Behavior

Just show me "Develop mod" menu

### Actual Behavior

Crashing

### Reproduction frequency

Always from 1.4.4 June stable update

**Comment by JavidPack** [comment]
Read the version section of https://github.com/tModLoader/tModLoader/wiki/build.txt#available-properties and fix the build.txt of your mod sources.

If you can't figure out which build.txt has an invalid version number, you can switch to the 2024.05 beta in the steam beta options since the preview version has additional logging.
