### ISSUE TITLE
Constant connection lost

### ISSUE THREAD

**Issue by MrDeath732** [bluemagic123/tModLoader#4368]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

When I load into a world me and my friend was play on "hell gambit" after a short period of time say 1 or 2 mins i would be in the world I'd get disconnected while having a stable internet connection the only major mod used in this world was ore excavator mod and spirit and this has just happened after the September state of the game update was released.

**Comment by JavidPack** [comment]
This issue is missing the logs files. Logs are necessary for us to help troubleshoot and fix this issue.
 
Please attach the log files. You'll find the log files in the logs folder. Look for the `client.log`, `Launch.log`, `Natives.log`, and `environment-client.log` files. If the issue relates to multiplayer post the `server.log` and `environment-sever.log` files as well.
      
Logs can be found in the "tModLoader-Logs" folder in your tModLoader [install directory](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#install) (to find your install directory on Steam right click on tModloader, then Manage and "Browse local files") 
      
Attach log files by making a new comment and dragging them into the text input field. Please do not copy and paste the text from the log files, post the actual files.
