### ISSUE TITLE
on Windows should check dotnet.exe and use where.exe, instead of "dotnet" and "where"

### ISSUE THREAD

**Issue by Dlinuigh** [bluemagic123/tModLoader#4461]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

I've installed dotnet sdk by vs installer. tml can't check this correctly. I looked up source code, and set DOTNET_ROOT environment variable to the right place. However, since dotnet on Windows is called by dotnet.exe, the method tml uses to find dotnet sdk by now is not always correct.
![image](https://github.com/user-attachments/assets/e8d7f0af-7fa5-4912-b680-b7971d46cd7e)

### Expected Behavior

Maybe I will pull a request, or just wait for any advice.

**Comment by Chicken-Bones** [comment]
The `DOTNET_ROOT` variable is only intended to help Linux resolution. Since you had to look up the tML source code to find it, you can imagine that other Windows users are not going to such lengths. 

The intended method for you is to put the folder containing `dotnet.exe` on your `PATH` environment variable. This should already be the case if `dotnet` works in `cmd.exe`. 

As far as I know, using the `.exe` suffix makes no difference to the resolution of commands on `PATH` on Windows. If you can run a C# snippet which proves otherwise I'll do more research.

If you need more help, please post a full `environment.log` and `client.log` file, and show us that `dotnet --list-sdks` works from a newly opened command prompt.

**Comment by Dlinuigh** [comment]
I solved this problem as follows:
> Set the DOTNET_ROOT environment variable (just an example, you can use the GUI editor to add this key-value pair):
```
set DOTNET_ROOT=C:\Program Files\dotnet
```
> Navigate to the .NET installation directory:
```
cd C:\Program Files\dotnet
```
> Create a symbolic link so that the program can recognize it:
```
mklink dotnet dotnet.exe
```
> Of course, to install the .NET SDK 8, you can use:
```
winget install Microsoft.DotNet.SDK.8
```

This shows that the DOTNET_ROOT environment variable is not restricted to Linux OS; the program will search this path for the dotnet executable.
