### ISSUE TITLE
Placing sand consumes inventory but sand does not place

### ISSUE THREAD

**Issue by Talamar1** [bluemagic123/tModLoader#47]
When trying to drop sand into place, my qty goes down but nothing places.  If I stand below and build the blocks upward, it works fine.
http://images.akamai.steamusercontent.com/ugc/254840656028138539/CB2AF2EFA93F7D48426118C39B5BC5C0DAC71924/

I'v also noticed that when mining silt or slush, hitting the bottom block causes the whole stack to disappear and nothing appears in your inventory.  It looks like something wrong with the falling block mechanic.

**Comment by Rahmiel** [comment]
I can confirm that this is happening with any physics based (natural) blocks. Silt, Sand, Slush all just poof instead of falling like they should. However, I do want to mention that coins behave properly, which is odd because they use the same physics. I'm not sure about @Talamar1 but this issue is only on servers for me.

**Comment by Talamar1** [comment]
Fixed in latest patch.
